### ISSUE TITLE
Running other neighborhoods

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#10]
## Germantown, Philadelphia, PA

_Note:_ For this job, ensure you first put the gtown_westside.osm file (on FILESHARE) into your `./data` directory. Alternatively, remove the `PFB_OSM_FILE` var from the command below.
```bash
docker run \
    -e PFB_SHPFILE=/data/gtown_westside.shp \
    -e PFB_STATE=pa -e PFB_STATE_FIPS=42 \
    -e NB_INPUT_SRID=4326 \
    -e NB_BOUNDARY_BUFFER=50 \
    -e PFB_OSM_FILE=/data/gtown_westside.osm \
    -e NB_OUTPUT_DIR=/data/output \
    -v /vagrant/data/:/data/ \
    pfb-analysis > pfb-analysis/germantown.log 2>&1
```

## Boulder CO

```bash
docker run \
    -e PFB_SHPFILE=/data/boulder.shp \
    -e PFB_STATE=co \
    -e PFB_STATE_FIPS=08 \
    -e NB_INPUT_SRID=4326 \
    -e NB_BOUNDARY_BUFFER=3600 \
    -e NB_OUTPUT_DIR=/data/output \
    -v /vagrant/data/:/data/ \
    pfb-analysis > pfb-analysis/boulder.log 2>&1
```

**Comment by CloudNiner** [comment]
These commands should be run inside the VM in the `/vagrant` dir

**Comment by CloudNiner** [comment]
If running the docker version, ensure your analysis image is up to date by first running `./scripts/update` or `docker build -t pfb .` within the VM.

**Comment by flibbertigibbet** [comment]
Due to the mount point, I think the first variable should be set like `-e PFB_SHPFILE=/data/boulder.shp` (root directory is `/data`, not `/vagrant`).

**Comment by CloudNiner** [comment]
Indeed. Updated.

**Comment by CloudNiner** [comment]
Updated:
- Use meters as units for NB_BOUNDARY_BUFFER
- Update name of docker image tag (`pfb` -> `pfb-analysis`) to match changes in #106

**Comment by CloudNiner** [comment]
This issue is superseded by README.RUNNING.md added in #136
