### ISSUE TITLE
Parameterize buffer distance in coverage.sql

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#114]
It doesn't look like this file is currently in use anywhere? Can you verify @spencerrecneps ?

**Comment by spencerrecneps** [comment]
Not currently. It's in need of some changes before I pull it into the final results. I'll parameterize appropriately when I make my updates.

**Comment by CloudNiner** [comment]
👍

**Comment by CloudNiner** [comment]
Leaving open for now and assigning to you. We can revisit this issue later.

**Comment by CloudNiner** [comment]
@spencerrecneps coverage.sql is still not used. Can that file be deleted if its not in use and this issue closed?

**Comment by spencerrecneps** [comment]
Yes. There are several files that are obsolete and can be removed. I'll do that and submit a PR.

**Comment by lydiascarf** [comment]
Closing this as it's about a file that doesn't exist anymore
