### ISSUE TITLE
Increase docker volume size in AWS

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#118]
In development, we provision docker with `--storage-opt dm.basesize=20G` to give us a bit more storage space to work with on the docker volume. Production jobs will require up to ~120GB of disk space, so we need to ensure we set the same parameter in production as appropriate, or investigate an alternate storage driver, since the default in ECS is also devicemapper due to the RHEL base image.

Potentially helpful documentation:
- https://docs.docker.com/engine/userguide/storagedriver/selectadriver/
- https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/
- http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html#ecs-ami-storage-config

**Comment by hectcastro** [comment]
Has this become a non-issue now?
