### ISSUE TITLE
Put "Running the analysis" and "Importing other neighborhoods" in the pfb-analysis README

### ISSUE THREAD

**Issue by KlaasH** [azavea/pfb-network-connectivity#120]
It appears I neglected to remove the README from the pfb-analysis directory when I moved it into this repo, so I was going to say we should add one there but we can just transform the (outdated) one that's already there.  Right now the description, usage information, and examples for the analysis are spread across the main README, issue #10, and various PRs that introduce new options but might not affect either of those so don't add any documentation outside the PR discussion.

I think it would make sense to move all of that into a README inside `pfb-analysis` (and linked from the main README) that includes the existing introduction (or one like it), documentation of all the arguments and variables that can affect the run, and an examples section that includes the ones in issue #10.

Aside from being useful in itself, this would make it easier to see the evolution of behavior and options, since they'd be documented in a tracked file when the changes happen.

**Comment by CloudNiner** [comment]
How difficult do you think this is? We have some additional PFB points left in the placeholder.

**Comment by KlaasH** [comment]
I think 1 point.  A bunch of moving things around followed by a bit of looking for undocumented parameters and writing a sentence or two about each.

**Comment by CloudNiner** [comment]
Agree. I'll update the placeholder and add to the sprint. This task is still a lower priority than the remaining pieces necessary to get an analysis running in AWS though.
