### ISSUE TITLE
Provide shell connection to analysis container

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/pfb-network-connectivity#125]
After an analysis run completes, the container exits. Due to the entrypoint configuration, there is no easy way to get back into the container with the completed run to evaluate results or run a one-off command.

Provide a means to connect to and run commands in the docker container for an existing analysis job. Possible solutions may be modifying the Docker `ENTRYPOINT` to simply provide a shell, and adding a `RUN` command to actually execute the analysis job; and/or add a script that gives a shell connection to the container for the last analysis job.

**Comment by CloudNiner** [comment]
Both the analysis container and the tilemaker container now drop into a shell via the `bash` instruction when run locally as long as the job is run via the `run-local-analysis` wrapper script.
