### ISSUE TITLE
Architect analysis tile generation

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#143]
How do we do this? Separate job? Same job? What additional software is necessary?

Need to output tiles for some number of sensible zoom levels depending on boundary size (2-5 levels) each time we run an analysis. Output uses the geom from neighborhood_ways table, polylines colored by one of the columns in the table.

**Comment by CloudNiner** [comment]
Consider asking other folks with tiling experience at Azavea for suggestions on how to handle this.

e.g. Geotrellis or people who worked on Tiler Perry

Task inputs:
- shapefile with linestring geometries, with the fields to style by as attributes

Task outputs:
- Static image tiles stored to the job's `results` S3 bucket, one tile layer, only saving a subset of sensible zoom levels for that particular location (base the zoom level range on boundary size?)

**Comment by CloudNiner** [comment]
@spencerrecneps The analysis database table we need to export for this is `neighborhood_ways` correct? Which columns should we be styling/displaying on that table? What are the possible values, and which values are 'good' and 'bad'?

**Comment by spencerrecneps** [comment]
@CloudNiner sorry I missed the mention above. Looks like you got this sorted out? There are actually two stress values that should be shown: ft_seg_stress and tf_seg_stress. The way I generally show these is to draw two lines (one for each side of the road) and offset them slightly.

**Comment by CloudNiner** [comment]
Thanks. Not quite what we're doing, added #261 to address it.
