### ISSUE TITLE
Add analysis status reporting to pfb-analysis scripts

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#145]
When we trigger an analysis job, we don't ever know when it finishes via the Django model, unless we directly poll for batch job status. The goal here is to have the analysis job report progress back to the Django model, so we have a better approximation of when each job completes without having to poll.

Create function that sends PATCH to /api/analysis-jobs/:jobId, call before starting each of the major sections of the analysis, updating AnalysisJob.status

Will require extra vars to be passed to the analysis job ENV.

**Comment by sharph** [comment]
Instead of above strategy, consider installing django app into analysis container and updating job status via management command.
