### ISSUE TITLE
Add tables to export

### ISSUE THREAD

**Issue by spencerrecneps** [azavea/pfb-network-connectivity#157]
The following tables should be made available via export:
- neighborhood_census_blocks
- neighborhood_colleges
- neighborhood_community_centers
- neighborhood_medical
- neighborhood_parks
- neighborhood_retail
- neighborhood_schools
- neighborhood_social_services
- neighborhood_supermarkets
- neighborhood_universities

**Comment by CloudNiner** [comment]
These tables should be exported back to the job S3 bucket, as geojson

**Comment by spencerrecneps** [comment]
Updated list of tables to export as shapefile/geojson:

- neighborhood_census_blocks
- neighborhood_ways
- neighborhood_colleges
- neighborhood_community_centers
- neighborhood_doctors
- neighborhood_dentists
- neighborhood_hospitals
- neighborhood_pharmacies
- neighborhood_parks
- neighborhood_retail
- neighborhood_schools
- neighborhood_social_services
- neighborhood_supermarkets
- neighborhood_universities

Updated list of tables to export as CSV:

- neighborhood_connected_census_blocks
- neighborhood_score_inputs
- neighborhood_overall_scores

**Comment by spencerrecneps** [comment]
Many of these tables were added to export_connectivity.sh by https://github.com/azavea/pfb-network-connectivity/pull/222

**Comment by CloudNiner** [comment]
I'm not sure what use the neighborhood_connected_census_blocks table is. For a boundary of any substance, this file will be many GB in size, so I'm not sure its worth exporting -- I'm not confident that a program like Excel will even open it successfully.

We also may not export neighborhood_census_blocks as geojson for the same reason.

What are your expected use cases for these two files?

**Comment by spencerrecneps** [comment]
In my demos with PFB I've been able to use neighborhood_connected_census_blocks to show the relative low stress and high stress bike shed around a given census block. The example image below illustrates the low stress bike shed in blue and the high stress bike shed in red for the origin census block outlined in bright pink.

![low and high stress bikesheds](https://cloud.githubusercontent.com/assets/4584258/24422759/4129fbbe-13c0-11e7-8608-dcbc10ff0cbc.png)

It's one of the features that seems to most impress them so I think it's important we offer the option to download it. Would it be possible to make it an optional part of the data export? Could we also zip the file to reduce the size of the CSV?

**Comment by spencerrecneps** [comment]
I'm also OK with not making neighborhood_census_blocks available as geojson as long as it can be downloaded as shapefile. To be honest, most cities are probably not going to know what to do with geojson anyway.

**Comment by CloudNiner** [comment]
Added #223 to separately address exporting connected_census_blocks
