### ISSUE TITLE
Large city Overpass API requests fail

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#176]
For example, when running the combined Manhattan/Brooklyn/Bronx area, [Overpass](http://www.overpass-api.de/api/xapi?*[bbox=-74.3680999189354,40.1958678567824,-73.4336916853588,41.2785587770841] ) returns a 200, but the downloaded file is XML with the following error:
```
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="Overpass API">
<note>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.</note>
<meta osm_base="2017-03-17T12:57:03Z"/>

<remark> runtime error: Query ran out of memory in "recurse" at line 11. It would need at least 513 MB of RAM to continue. </remark>

</osm>
```

We should detect these errors and log a helpful warning. We also need an alternative way to get OSM data for these analysis areas.

**Comment by spencerrecneps** [comment]
The osm2pgrouting and osm2pgsql allow for input from an .osm file, right? Could we allow for an .osm file to be placed in /data and pointed to with a command line option?

**Comment by CloudNiner** [comment]
Correct. That is already supported in the analysis, need to build out the web application to support it as well.

**Comment by CloudNiner** [comment]
Another option to explore is using a different request format, which may allow a larger area extract, as is done on another project:
```
curl 'http://overpass-api.de/api/interpreter?data=(node(39.467695,-76.209582,40.725449,-74.243725);way(39.467695,-76.209582,40.725449,-74.243725);relation(39.467695,-76.209582,40.725449,-74.243725););out;' -o boundary-extract.osm
```
