### ISSUE TITLE
ERROR: Syntax error at or near "*" at character 9

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#228]
In reachable_roads_low_stress.sql. Occurred during manhattan/bronx/brooklyn run.

Full trace:
```
21:24:14
ERROR: syntax error at or near "*" at character 9

21:24:14
STATEMENT: select (*) from neighborhood_reachable_roads_high_stress;

21:25:12
ERROR: canceling statement due to user request

21:25:12
STATEMENT: select count(*) from neighborhood_reachable_roads_high_stress;

23:09:50
INSERT 0 595074

23:11:10
INSERT 0 572872
```

**Comment by spencerrecneps** [comment]
This error doesn't seem to come from the sql code itself. Looks like a badly constructed SQL statement during one of the reporting tasks or something. Am I understanding that correctly?

**Comment by CloudNiner** [comment]
Not actually sure what is triggering this, and don't see anything in those sql scripts that would cause it. Will keep this open in case it surfaces again, but we won't look into it further at this point.

**Comment by CloudNiner** [comment]
Still unable to reproduce, closing
