### ISSUE TITLE
Move out of the AWS SES Sandbox

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#239]
For the PFB account, follow: http://docs.aws.amazon.com/ses/latest/DeveloperGuide/request-production-access.html

**Comment by CloudNiner** [comment]
I set up the SNS notification topic and subscribed both @KlaasH and myself to it.

The sending limit increase form requests the website URL, and we have not received it yet. The remainder of this task is blocked until we get the final hostname for the application from PFB.

**Comment by jcahail** [comment]
url will be http://bna.peopleforbikes.org/

**Comment by CloudNiner** [comment]
@azavea/operations requested the sending rate limit increase, which was applied successfully awhile back to the PFB AWS account. To finish this issue, I just did the following:
- Create new SES domain bna.peopleforbikes.org
- Create new pfb-ses-deliveries SNS topic and subscribe myself and @KlaasH to it
- Use pfb-ses-bounces topic for bounces/complaints and pfb-ses-deliveries for delivery for the new domain

All done within the console.

The production configuration still routes to the old domain, will update to the new email domain on the next deployment and close this issue at that time.
