### ISSUE TITLE
Jobs Stuck at "Generating Tiles"

### ISSUE THREAD

**Issue by spencerrecneps** [azavea/pfb-network-connectivity#270]
I ran several test areas on the staging website yesterday. One (Madison) completed just fine. The others all say "Generating Tiles" and have done all day. The job info page doesn't include any results. It appears these are either stuck or have finished without updating the results.

**Comment by CloudNiner** [comment]
Main issue here is that if more than one job is queued and the first job takes longer than 1hr to run, then the neighborhood zipfile presigned url expires before jobs get taken. Default url expiry is 1hr. Likely safe to just bump to a much higher value, we don't need to protect these files. I can patch that today.

Two other less critical bugs were exposed, created #272 and #273 to address those.
