### ISSUE TITLE
Last status is TILING if analysis jobs fail and report ERROR

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#272]
From failed job UUID `f454762d-7d7f-478c-9ade-6ac1159d2558` on staging:
```
>>> for u in job.status_updates.all():
...     u.status
...
u'QUEUED'
u'IMPORTING'
u'ERROR'
u'TILING'
```

We should guard against running the tiling step for jobs that fail their analysis step.

**Comment by spencerrecneps** [comment]
Has this issue resurfaced? There's a Boulder job that has been stuck on TILING all weekend. Also appears to be holding up a new job for Glendale, AZ that I just submitted.

**Comment by spencerrecneps** [comment]
Looks like it's not actually holding up Glendale, but the status is still TILING.

**Comment by CloudNiner** [comment]
You are correct, this issue is to treat the root cause of failed jobs ending up with TILING status, there are still a bunch of errors that could lead to this. Looks like both your most recent Boulder and Glendale runs threw errors during the analysis step. Opened #295 to look at the Glendale problem separately.

**Comment by KlaasH** [comment]
- Make run_analysis return non-zero status on error
- Put a wrapper in the tiling entrypoint to update status to error if it fails (and also return failing status)
