### ISSUE TITLE
Break retail score into separate category

### ISSUE THREAD

**Issue by spencerrecneps** [azavea/pfb-network-connectivity#281]
PFB has requested that I break the retail score out into its own category. Is this going to cause serious issues for you either on frontend development or any backend processes that work with the scoring categories?

**Comment by CloudNiner** [comment]
Retail is currently a single geojson file. How many sub scores in the new retail category are you planning on adding?

Note that if we're planning on displaying every single available destination as an option on the map, that we're already up to a dozen or so. If splitting retail leads to more than one or two more files, that selector will get pretty unwieldy as well.

**Comment by spencerrecneps** [comment]
It wouldn't have any subcategories. It would just live as its own score instead of being a part of the Opportunity score.

I'm not convinced this is actually a good change so I'm going to try to dissuade Jennifer, but does this create much trouble for you if we go ahead with it?

**Comment by CloudNiner** [comment]
No if the output destinations files remain the same then its not a huge issue. We'll need to update the score metadata we're maintaining, if you can do so as part of your changes that would be great. That file lives here:
https://github.com/azavea/pfb-network-connectivity/blob/develop/src/django/pfb_analysis/fixtures/analysis-score-metadata.json

**Comment by KlaasH** [comment]
Resolved by PR #294.
