### ISSUE TITLE
Glendale AZ job fails with reprojection error in neighborhood_pharmacies geojson export

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#295]
Glendale job failed because the neighborhood_pharmacies table threw a reprojection error when attempting to export that table as geojson.

https://staging.pfb.azavea.com/#/admin/analysis-jobs/d95d0f71-21e3-4088-8fc8-6df10226ec47/

[AWS Log](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/batch/job;stream=staging-pfb-analysis-run-job--219--d95d0f71/c57348fa-5460-4d25-b37e-0040ecd44931/f16fe022-dabd-463a-ba2c-232b8734a082)

Full log:
```
14:03:06
EXPORTING: neighborhood_pharmacies

14:03:06
Warning 1: More than one geometry column was found in the result of the SQL request. Only last one will be used

14:03:06
Warning 1: More than one geometry column was found in the result of the SQL request. Only last one will be used

14:03:06
translation from sql statement.
translation from sql statement.

14:03:06
Failed to reproject feature 11 (geometry probably out of source or destination SRS).
Failed to reproject feature 11 (geometry probably out of source or destination SRS).

14:03:06
ERROR 1: Terminating translation prematurely after failed

14:03:06
ERROR 1: non-convergent inverse meridional dist

14:03:06
LOG: unexpected EOF on client connection with an open transaction

14:03:06
Updating job status: ERROR Failed See job logs for more details.

14:03:06
LOG: received fast shutdown request
```

**Comment by CloudNiner** [comment]
Best way to get at postgresql database that ran the job (?):
- S3 cp the data dir on the AWS machine that ran the job to some path on S3
- S3 cp those same files to your local instance
- Start a postgresql container with PGDATA set to wherever you copied the data dir to locally
- Inspect tables via psql

Instead of using s3 as the intermediary, maybe theres a way to stream data through the bastion to local machine via SCP, without copying data to the bastion disk (which doesn't have enough disk space for the larger analysis runs)

**Comment by spencerrecneps** [comment]
@CloudNiner are you planning to inspect this yourself? Not sure I'm capable of copying down the data dir and restoring locally.

**Comment by CloudNiner** [comment]
yeah, we're going to attempt to take a look
