### ISSUE TITLE
Run first Batch Analysis

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#310]
Depends on #313 #307 #308 #297 

Steps:
- Complete dependent tasks
- Scale up batch cluster ASG to 20 workers
- Trigger Batch via management command
- 👀

**Comment by jcahail** [comment]
Run Big Jump shapefiles Friday, use 1-2 batch worker instances

Present results to Jennifer

**Comment by CloudNiner** [comment]
To complete this task, I did the following:
- Request instance type increase for `i3.2xlarge` instances on the PFB AWS account (which was approved a few hours later)
- Manually set the production batch ASG to 6 instances
- SSH into Django worker to run:
  - `./manage.py analysis_batch_create --submit https://s3.amazonaws.com/pfb-batch-run-inputs-us-east-1/2017_04_26_PFB_Neighborhood_Cities_Round1_withOSM.zip`
  - `./manage.py analysis_batch_create --submit https://s3.amazonaws.com/pfb-batch-run-inputs-us-east-1/2017_04_26_PFB_Neighborhood_Cities_Round2_withOSM.zip`
- Wait for jobs to complete or fail
- Created new issues #358 #359 #360 to address fallout

Ran successfully:
- Fort Collins, CO
- Providence, RI
- Memphis, TN
- Tuscon, AZ
Still running:
- New Orleans, LA (generating tiles)
- Portland, ME (generating tiles)
Failed:
- New York City,NY (disk error)
- Los Angeles, CA (disk error)
- Austin, TX (disk error)
- Baltimore, MD (disk error)
