### ISSUE TITLE
Batch Analysis placeholder

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#311]
Time to resolve issues/errors with jobs in the batch analysis, back and forth with spencer, etc

**Comment by CloudNiner** [comment]
8 points, Sprint ending 5/4/2017

**Comment by CloudNiner** [comment]
-1 for #349 

7 points remaining

**Comment by CloudNiner** [comment]
-1 for #350 

6 points remaining

**Comment by CloudNiner** [comment]
-2 for #343 

4 points remaining

**Comment by CloudNiner** [comment]
-1 for #358

**Comment by CloudNiner** [comment]
-1 for #367 

2 points remaining

**Comment by CloudNiner** [comment]
-1 for #377 

1 point remaining

**Comment by flibbertigibbet** [comment]
Point for issue #377 (PR #374) was deducted from azavea/urban-apps#33, so I think that can be added back here, unless we're counting against both placeholders.

**Comment by CloudNiner** [comment]
azavea/urban-apps#33 was for the sprint ending 4/20, so this is the correct placeholder. sorry for the confusion!
