### ISSUE TITLE
Import Route 53 hosted zone for bna.peopleforbikes.org with Terraform

### ISSUE THREAD

**Issue by hectcastro** [azavea/pfb-network-connectivity#317]
Use the Terraform `import` subcommand to update the Route 53 hosted zone used for the production environment:

```bash
$ terraform import aws_route53_zone.external Z84UZTEOSPION
```

Also includes:

- [x] Increasing SES email sending limits
- [ ] Requesting ACM wildcard certificate for `*.bna.peopleforbikes.org `

**Comment by CloudNiner** [comment]
Does doing `terraform import` make sense over updating the hostname in production tfvars and letting Terraform create the hosted zone?

Also need to make sure we generate a new SSL cert for the domain and add it to tfvars as well.

Issue is not high-priority at the moment, I'd say as long as we have this done by May 4, we're fine. That should give plenty of time to get email sending limits approved before the May 24 deliverable.

**Comment by hectcastro** [comment]
> Does doing `terraform import` make sense over updating the hostname in production tfvars and letting Terraform create the hosted zone?

Main reason I took this approach was to be able to create the hosted zone manually without making the current production stack go dark. I wanted to get my hands of the set of NS records right away so that we can start the sometimes long process of getting root domain DNS records updated.

Good point about the ACM certificate setup. Likely we'll have to create that when we get on an email thread with them because the request expires in 72 hours.

**Comment by CloudNiner** [comment]
re: `terraform input`. That works. We should just make sure to document differences in the deployment process due to this change. Alternatively, it would be fine if the production stack went down today to apply this change the proper way within the terraform environment.

**Comment by tnation14** [comment]
The new hosted zone is now managed by terraform. The old zone is no longer managed by terraform, but it hasn't been deleted. I also added the new hosted zone name to the production `.tfvars` file.

**Comment by hectcastro** [comment]
Case was created with AWS to get us out of the SES sandbox.

**Comment by CloudNiner** [comment]
👍 thanks hector!

**Comment by tnation14** [comment]
Production is available at https://bna.peopleforbikes.org.

**Comment by CloudNiner** [comment]
Keep me posted on progress on this and when you plan to update the production tfvars to point back to bna.peopleforbikes.org. I just pushed 0.1.2 to master and deployed to production to prepare for running our first round of batch analyses.

**Comment by tnation14** [comment]
Production tfvars are updated; if you deployed after 12:25 PM today the hosted zone should be correct.

**Comment by CloudNiner** [comment]
Indeed it is. Missed that. Thanks.

**Comment by hectcastro** [comment]
Just sent off the instructions to approve the ACM request. After that's complete, we'll be good to close this out.
