### ISSUE TITLE
Descending sort on analysis job scores orders nulls first

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/pfb-network-connectivity#322]
Ordering for highest scores first with: http://localhost:9200/api/analysis_jobs/?ordering=-overall_score

Returns jobs with no score first. Jobs missing scores should sort to end of descending list.

**Comment by CloudNiner** [comment]
We now filter so that we only show completed jobs in the UI. It's not possible for a job to be complete and still have null scores.
