### ISSUE TITLE
Implement section headers on places list view in UI

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#326]

**Comment by CloudNiner** [comment]
@jcahail should the section headers only exist for the "alphabetical" sort option?

**Comment by jcahail** [comment]
There should also be one for "population" sort option (headers= large, medium, small)

**Comment by CloudNiner** [comment]
Right. Where did they decide what the population thresholds should be for small/medium/large? I don't see anything in issues.

**Comment by jcahail** [comment]
https://github.com/azavea/pfb-network-connectivity/pull/300

"Current breaks are set at >= 500,000 (large city) and >= 100,000 (medium city)."

**Comment by CloudNiner** [comment]
Whoops. Thanks!
