### ISSUE TITLE
Add copy to Methodology page of public site

### ISSUE THREAD

**Issue by jcahail** [azavea/pfb-network-connectivity#344]
[Methodology for Website Final.docx](https://github.com/azavea/pfb-network-connectivity/files/952736/Methodology.for.Website.Final.docx)
[Scoring categories.xlsx](https://github.com/azavea/pfb-network-connectivity/files/952739/Scoring.categories.xlsx)
[OSM Tags.xlsx](https://github.com/azavea/pfb-network-connectivity/files/952740/OSM.Tags.xlsx)
[Charts for LTS Definitions 2017-0403.xlsx](https://github.com/azavea/pfb-network-connectivity/files/952741/Charts.for.LTS.Definitions.2017-0403.xlsx)

**Comment by flibbertigibbet** [comment]
Requires adding a methodology page.
