### ISSUE TITLE
Change base map

### ISSUE THREAD

**Issue by KlaasH** [azavea/pfb-network-connectivity#345]
While looking at the tile styling, @designmatty and I observed that the somewhat-dark roads on Stamen Toner Lite made it harder to see the segment stress layer.  He suggested [Positron](https://leaflet-extras.github.io/leaflet-providers/preview/#filter=CartoDB.Positron) instead.  Not sure if that was a "let's use this" or "let's try this to see if it looks better" suggestion, but in any case it makes sense to switch to something with outline rather than solid roads.

**Comment by designmatty** [comment]
I imagine Positron would be our best bet since it's a very subdued basemap and would push the focus on the stress layer. I have no issues with using it right away.
