### ISSUE TITLE
Add copy to Homepage re: How the Bike Network Score is Calculated

### ISSUE THREAD

**Issue by jcahail** [azavea/pfb-network-connectivity#348]
[How the score is calculated for website Final.docx](https://github.com/azavea/pfb-network-connectivity/files/955871/How.the.score.is.calculated.for.website.Final.docx)

**Comment by flibbertigibbet** [comment]
Modify section header to: "How the BNA Score is calculated".

And add line of text below the metric description cards that links to the methodology:
"Our process is described in more detail, including a full technical summary, here <link to methodology page>."
