### ISSUE TITLE
`recreation` and `core_services` overall score calculations keep trying to divide by zero

### ISSUE THREAD

**Issue by KlaasH** [azavea/pfb-network-connectivity#370]
dc0e5f4, from PR #290, introduced denominators to some of the calculations in `overall_scores.sql`, I think with the goal of weighting scores by the connectivity of services that are actually present in the boundary rather than averaging in zeroes for things that don't apply.

But in the case of `recreation` and `core_services` there's no unconditional term in the parts that go into the denominator, so if a neighborhood has none of the things getting scored, it tries to divide by zero and the analysis crashes.

It may be that this only happens when something has gone wrong and there will never be a case where OSM data has loaded properly and a denominator still ends up blank.  But unless we can guarantee that we should protect against it, and in any case it's not a very good failure mode.

**Comment by CloudNiner** [comment]
This issue caused a single failure for the neighborhood 'Soldotna AK' in the first batch run. We'll need to rerun a job for that boundary once this fix is pushed.

**Comment by CloudNiner** [comment]
Closed by #372
