### ISSUE TITLE
Coordinate system handling

### ISSUE THREAD

**Issue by spencerrecneps** [azavea/pfb-network-connectivity#39]
My original code used a local coordinate system with units in US Feet. I'm wondering how this has been dealt with in your adaptation? There are a few instances where we use spatial measurements in the units of the coordinate system (e.g. for buffering). Obviously, this can introduce error if the coordinate system used is not in US Feet.

In retrospect, it would probably have been best to use 3857 in meters so as to avoid needing to gather a local SRID as input. Is this a change I should make in my code? Or have you already implemented your own fix?

I don't want to create massive incompatibilities between our code bases so if you've already handled this elegantly I'll ignore. But ideally, I'd like to switch over to 3857 and meters.

**Comment by CloudNiner** [comment]
We will continue to use UTM.

Opened #42 to add a way to autodetect the correct SRID from the input boundary file.
