### ISSUE TITLE
Sort places list by population

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/pfb-network-connectivity#395]
Implement sorting analysis jobs by related metadata population for neighborhood in backend and the places list UI. Add sub-headings to list results in UI for the three population categories (small, medium, and large.)

See comment on #380. This issue is for item 5 in document attached to that issue.

**Comment by CloudNiner** [comment]
- [ ] Add sorting option in Django filter
- [ ] Add option to places list sort dropdown

Sub-headings to list results is a separate issue: #326

**Comment by KlaasH** [comment]
See https://github.com/azavea/pfb-network-connectivity/blob/develop/src/django/pfb_analysis/models.py#L245, where we use an annotation to pull `overall_score` out of the json field into a sortable/filterable property.
