### ISSUE TITLE
Upstream commit to change global SRID

### ISSUE THREAD

**Issue by spencerrecneps** [azavea/pfb-network-connectivity#40]
New commit upstream changes SRID from local coordinate system in US Feet to 3857 in meters. This eliminates the need for a parameterized SRID since it applies worldwide. Spatial measures have also been converted from feet to meters. 

See #39 for relevant discussion.

**Comment by CloudNiner** [comment]
@spencerrecneps due to our concerns in #39, we will not be pulling in this upstream change and will continue to use local UTM as the SRID for the network analysis.

#42 will allow us to automatically detect and set the SRID for the analysis based on the input neighborhood shapefile.
