### ISSUE TITLE
Sprint plan 12/28

### ISSUE THREAD

**Issue by jbranigan** [azavea/pfb-network-connectivity#41]
- [ ] analysis docker container
- [ ] bring pfb submodule up to date
- [ ] set up celery worker process
- [ ] django api endpoint to trigger job
- [ ] staging terraform deployment (ecs, web celery tasks, db)
- [ ] super basic angular ui to trigger job
- [ ] aws monitoring to track job run times (or some sort of logging, probably set up in terraform)
- [ ] dump analysis db to s3 (or some other persistent storage)

**Comment by CloudNiner** [comment]
Closing this as its out of date.
