### ISSUE TITLE
Implement/fix map on places list page

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#418]
It's blank, no console errors
![screen shot 2017-05-10 at 15 07 25](https://cloud.githubusercontent.com/assets/1818302/25916382/6e65824e-3592-11e7-94c2-1515f013a042.png)

**Comment by CloudNiner** [comment]
Map functionality should be the following:
- A marker for each neighborhood shown in the list sidebar
- Markers should filter along with the list when filtering occurs
- Map should always show any neighborhoods selected for comparison

**Comment by flibbertigibbet** [comment]
Production-only issue

**Comment by flibbertigibbet** [comment]
Fixing the styling seems to be a different issue from implementing the two new features listed above (filtering markers with list, and showing on map those selected for comparison.)

Also not sure what is meant by "Map should always show any neighborhoods selected for comparison."
