### ISSUE TITLE
Places list page makes a request which pulls all neighborhoods

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#419]
https://bna.peopleforbikes.org/#/places//// requests:

https://bna.peopleforbikes.org/api/neighborhoods/?limit=all

Which takes 4+seconds on production. We can likely refactor this to only pull the neighborhoods we need, as this list view should be paginated.

**Comment by flibbertigibbet** [comment]
Likely that request is made in order to populate search bar filter.

The list view is paginated; the data in it comes from the analysis jobs endpoint, however, and not neighborhoods directly.

**Comment by CloudNiner** [comment]
Ah that makes sense. This issue might resolve itself then if we address #420
