### ISSUE TITLE
Autodetect UTM zone before analysis

### ISSUE THREAD

**Issue by jbranigan** [azavea/pfb-network-connectivity#42]
Figure out the SRID based on lat/lon

UTM zone 10N is 32610
UTM zone 10S is 32710

Reference for ideas:
https://github.com/jbranigan/geo-scripts-python/blob/master/latlng2utm/detect-utm-zone.py

**Comment by spencerrecneps** [comment]
I gather this means we will continue to use meters as the unit for measuring distances? I think that's a good thing, but we will need to incorporate some of the changes from #39 that swapped calculations from feet to meters.

**Comment by spencerrecneps** [comment]
The commit on my repo can be seen here: https://github.com/spencerrecneps/pfb/commit/e1c7d31100f73e68d29bcd72c8f31e7e40d19c8d

**Comment by CloudNiner** [comment]
Yes, that seems correct. We'll have to make those ft -> m changes as part of this task, otherwise measurements would be wrong if brought in as part of azavea/pfb#10
