### ISSUE TITLE
Show generated tiles on detail map

### ISSUE THREAD

**Issue by KlaasH** [azavea/pfb-network-connectivity#426]
See PR #354 for URL pattern.

**Comment by CloudNiner** [comment]
Place these in the 'baselayer' section of the layer control using radio buttons

Move the area boundary to the 'baselayer' section as well.

Don't include the positron layer in the picker.

**Comment by flibbertigibbet** [comment]
I believe making the area boundary a base layer means that if selected, no base map will display (just the area). If we want to always display the boundary as a non-selectable item, we could just not add it to the layer tool (only add it to the map).
