### ISSUE TITLE
Double tooltips (and placeholder text)

### ISSUE THREAD

**Issue by KlaasH** [azavea/pfb-network-connectivity#439]
![image](https://cloud.githubusercontent.com/assets/6598836/26005186/4bf5b088-3706-11e7-9663-0a00fc3c2065.png)

There are two problems with this picture.
- the browser tooltip comes up after a second and covers the javascript tooltip
- placeholder text

**Comment by CloudNiner** [comment]
Looks like Firefox? 

Also happens in Chrome, but the browser tooltip is delayed an extra few seconds and doesn't cover as much as the custom tooltip.
