### ISSUE TITLE
Compare boxes should be blue when selected

### ISSUE THREAD

**Issue by KlaasH** [azavea/pfb-network-connectivity#441]
In messing around to check PR #438, I found the behavior/styling of the compare boxes confusing.  Especially when I had selected three and wanted to unselect one of them and select another, having everything gray made it hard to figure out where to click.

Here's how it is now:
![image](https://cloud.githubusercontent.com/assets/6598836/26008546/466ab354-3713-11e7-85c7-1b55edcf098c.png)

Here's how I think it should be:
![image](https://cloud.githubusercontent.com/assets/6598836/26008566/51c259a0-3713-11e7-82d6-606ae20f9aa4.png)

Here's the diff I used to make the second one happen, in [`place-list.html`](https://github.com/azavea/pfb-network-connectivity/blob/develop/src/angularjs/src/app/places/list/place-list.html#L92):
```diff
  <div class="compare">
      <button ng-if="!placeList.isInPlaceCompare(neighborhood.uuid)"
+             class="btn btn-toggle"
              ng-disabled="placeList.isPlaceCompareFull()"
-             ng-class="(placeList.isPlaceCompareFull()) ?
-                 'btn btn-toggle' : 'btn btn-toggle active'"
              ng-click="placeList.addPlaceToCompare(neighborhood)">Compare
          <span></span>
      </button>
      <button ng-if="placeList.isInPlaceCompare(neighborhood.uuid)"
-             class="btn btn-toggle"
+             class="btn btn-toggle active"
              ng-click="placeList.removeComparePlace(neighborhood.uuid)">Remove
          <span></span>
      </button>
```

**Comment by designmatty** [comment]
This was fixed with #443
