### ISSUE TITLE
Replace PlacesForBikes logo with PeopleForBikes logo throughout site

### ISSUE THREAD

**Issue by jcahail** [azavea/pfb-network-connectivity#448]
brand assets: https://drive.google.com/open?id=0Bwh7HUe_vplea3Y3bUhTb1poWDRtVkdRc2ZsUUF0akdHdWpn

**Comment by CloudNiner** [comment]
@jcahail can they provide the image assets that they'd like us to use? The brand guide is a PDF, there's not website assets provided.

@designmatty if any of the images are displayed via angular, feel free to ask in the channel for developer support to get the images switched out.

**Comment by jcahail** [comment]
logos: https://drive.google.com/drive/folders/0Bwh7HUe_vplebXdCd1RydS0tb2c?usp=sharing
