### ISSUE TITLE
Remove duplicates

### ISSUE THREAD

**Issue by jcahail** [azavea/pfb-network-connectivity#453]
- [x] Tucson
- [x] Los Angeles

**Comment by CloudNiner** [comment]
Check which name is used in the source batch shapefiles on the fileshare and delete the neighborhood that doesn't match. Or, check which analysisjob is more recent and delete the older one, then update the shapfile city field to match.

**Comment by CloudNiner** [comment]
Additional duplicates:
- [ ] Austin, TX

**Comment by CloudNiner** [comment]
The duplicates indicated above were deleted by deleting the neighborhood with the older `n.created_at` date.

Verified that no more duplicates existed as part of #449
