### ISSUE TITLE
Align bottom of maps on compare page

### ISSUE THREAD

**Issue by jcahail** [azavea/pfb-network-connectivity#456]
![image](https://cloud.githubusercontent.com/assets/24727081/26119581/ade75872-3a3b-11e7-87b0-8ff38fb3f376.png)

**Comment by flibbertigibbet** [comment]
Tried loading Avondale locally, but could not reproduce issue (all thumbnail maps are same size and alignment.)

**Comment by flibbertigibbet** [comment]
Avondale is missing the 'Trails' score on staging. Manually adding a list element for the score fixes the map height, so addressing #502 should fix this issue.
