### ISSUE TITLE
Indent subscore categories on Compare page

### ISSUE THREAD

**Issue by jcahail** [azavea/pfb-network-connectivity#457]
Indent the subscores for the network categories (e.g., “Dentists” through “social services” are part of the Core Services score--indent those)

**Comment by CloudNiner** [comment]
Depends on #466

**Comment by CloudNiner** [comment]
Fastest solution is likely to add a `subscore: 1` to the API response for AnalysisScoreMetadata that is one if subscore, 0 otherwise. Then use that to apply a class that throws some padding-left on subscore categories.

I can walk you through which scores are subscores if you're unsure.

**Comment by CloudNiner** [comment]
Score tree is as follows:
- Core Services Total
  - Dentists
  - Doctors
  - Grocery
  - Hospitals
  - Pharmacies
  - Social Services
- Opportunity Total
  - Employment
  - Higher Education
  - K12 Education
  - Tech/Vocational College
- Recreation Total
  - Community Centers
  - Parks
  - Trails

Any other score not included here should be considered a top level category and _not_ be indented.

**Comment by jcahail** [comment]
^^ Correct.

**Comment by flibbertigibbet** [comment]
Should there be section headers for the categories? And should the same layout apply to the place detail page, where the scores are also displayed as a list?

**Comment by jcahail** [comment]
I would opt for (1) not adding section headers for the categories and (2) applying the same layout to the place detail page.

**Comment by flibbertigibbet** [comment]
Okay. I take it we want to indent under the 'total' score, for categories which have a total.
