### ISSUE TITLE
Reorder scores on Compare page

### ISSUE THREAD

**Issue by jcahail** [azavea/pfb-network-connectivity#458]
[ ] Change “Overall score” to “BNA Score” and move to top of the list
[ ] Move "Total population" to second on the list
[ ] Move "People" to third on the list

**Comment by CloudNiner** [comment]
This may conflict in some way with #457, as the request to indent subcategories implies that those subcategories will be sorted underneath the parent category. We may need to communicate with them about the ordering before implementing this

**Comment by jcahail** [comment]
Order should be:
BNA Score (currently Overall Score)
Total Population
People
Core Services
        Dentists
        Doctors
        Grocery
        Hospitals
        Pharmacies
        Social Services
Opportunity Total
        Employment
        Higher Education
        K12 Education
        Tech/Vocational College
Recreation Total
        Community Centers
        Parks
        Trails
Retail
Transit
