### ISSUE TITLE
Zero value in city population

### ISSUE THREAD

**Issue by spencerrecneps** [azavea/pfb-network-connectivity#476]
The cities all show a value of zero for population. As far as I can tell, the population is being correctly generated in the neighborhood_overall_scores table so I'm guessing it's a problem somewhere in the extraction of the scores.

Unfortunately, I can't download the overall_scores.csv files to verify thanks to https://github.com/azavea/pfb-network-connectivity/issues/463

**Comment by CloudNiner** [comment]
This should be closed by #474, it looks like a bug in the way we render scores on the public site.

**Comment by CloudNiner** [comment]
Closed by #474 and #469
