### ISSUE TITLE
Add link to improve OSM in map

### ISSUE THREAD

**Issue by spencerrecneps** [azavea/pfb-network-connectivity#485]
We would like to have a link on the web map for people to click if they want to make improvements to OSM. The use case is that someone sees that a bike lane is missing and wants to add it, so they can click the link and learn how to make OSM edits.

I've seen something like this on Mapbox maps:
![image](https://cloud.githubusercontent.com/assets/4584258/26359614/8c885dce-3f9b-11e7-9a6c-a8dcc488fcc7.png)

If this can easily be added to the attribution it would be great to have. If adding to the attribution is more than a minimal effort, another suitable alternative would be to add a link and text that says "See something missing from your bike network? Learn how to make updates _here_." The link should go to http://learnosm.org/en/
Ideally, this would be added on the neighborhood detail page above or underneath the map. Alternatively, this could be added at the bottom of the About page under the "Our process is described in more detail, including a full technical summary, here."

**Comment by CloudNiner** [comment]
Result of discussion this AM is to add a link to http://learnosm.org/en/ with the text "Improve this map" to either the left or right side of the map attribution on the place detail page.
