### ISSUE TITLE
Improve geometry simplification in pfb_analysis.models.simplify_geom

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#488]
In #452 we ran one-off scripts against the existing neighborhoods in production to clean up Neighborhood simple geometries broken by the existing simplify_geom algorithm. 

The algorithm in simplify_geom should be updated once we have insight into whether it makes sense to just always use preserve_topology with the lower simplification tolerance. Is it worth keeping the existing logic around? Does preserve_topology lead to geojson geometries that are too large to serve/display?

**Comment by flibbertigibbet** [comment]
Preserving topology does result in larger shapes and also makes the simplification take longer to run. However, as we apparently are getting complex multipolygons that require preservation, I think it makes sense to always preserve topology.

An easy test for whether to preserve or not might be to simply check whether we got a simple polygon or a multipolygon as the input shape, if we want to retain some fallback mechanism, although I suppose it's still possible a single polygon might also require preservation. As we were able to address a number of performance issues elsewhere, however, always preserving may be fine for our purposes.

**Comment by CloudNiner** [comment]
The [Fayetteville, AR boundary](https://production-pfb-storage-us-east-1.s3.amazonaws.com/neighborhood_boundaries/fayetteville/fayetteville.zip) exhibits issues with simplification as well. It is a two polygon geometry where each polygon is disjoint:

![screen shot 2017-10-10 at 16 01 51](https://user-images.githubusercontent.com/1818302/31408005-00ad21ec-add5-11e7-9896-3395f4eec7ff.png)

When simplified via the simplify_geom method, the simplification algorithm targets the second smaller polygon and removes the larger one. If we attempt to do the same simplification, but instead use tolerance SIMPLIFICATION_TOLERANCE_LESS via `simple = MultiPolygon([geom.simplify(SIMPLIFICATION_TOLERANCE_LESS)])` we get the error `TypeError('Invalid type encountered in the arguments.')`. Which is because the simplification returns a MultiPolygon instead of a Polygon. Just doing `simple = geom.simplify(SIMPLIFICATION_TOLERANCE_LESS)` works correctly because we're going directly between instances of MultiPolygon.

I fixed the simple_geom for this boundary manually, but any fix to the more general case would need to catch this particular problem as well.

**Comment by CloudNiner** [comment]
Suggested solution is to check simplified area against original area. If below some threshold fall back to lower tolerance and preserve topology.
