### ISSUE TITLE
Add "Compare" button to Details page

### ISSUE THREAD

**Issue by jcahail** [azavea/pfb-network-connectivity#489]
Compare button should direct user to Compare page.

N.b., The compare button was in the original wireframes, but was replaced with the Download button in a marked up wireframe from the client. Client would like the compare button restored and placed next to the Download button.

![image](https://cloud.githubusercontent.com/assets/24727081/26370131/e98a17b4-3fc4-11e7-8886-dbc4cb28e295.png)

**Comment by CloudNiner** [comment]
This button should always be active, and should link to the compare page, where the neighborhood currently being displayed on the detail page is placed into the first compare slot.
