### ISSUE TITLE
Edit link to feedback survey

### ISSUE THREAD

**Issue by jcahail** [azavea/pfb-network-connectivity#498]
Should point to http://www.peopleforbikes.org/placesforbikes/pages/bicycle-network-analysis

**Comment by CloudNiner** [comment]
Can this be added to the 6/23 milestone and addressed next sprint?

**Comment by jcahail** [comment]
Sadly, I don't think so. According to the new timeline, (1) they're relying on this feedback to assess the tool's success before the larger, public launch and (2) the 6/23 milestone will be revised to 8/4 (awaiting confirmation on that).

**Comment by CloudNiner** [comment]
Ok. Just finished another task, I'll address this now.

**Comment by CloudNiner** [comment]
Closed by #499
