### ISSUE TITLE
Add additional bike infrastructure tile layer

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#504]
postgres column to style mappings coming from @spencerrecneps and PFB

Need styling

Task includes:
- Creating new tilemaker job
- Adding tilemaker style file
- Adding layer to detail map layer picker

**Comment by CloudNiner** [comment]
Blocked by contract amendment

**Comment by jcahail** [comment]
From @spencerrecneps : Regarding the bike infrastructure map layer, the ways layer has a column with various bike facilities. The values for which we should display symbols are:
·         lane
·         buffered_lane
·         track

We should also offset the lines as we do with the Stress layer. As for symbol styles, we generally do a thinner blue line for bike lanes, a thicker, darker blue line for buffered lanes, and a thicker, darker blue line with a thin dashed white line running down the middle.

@spencerrecneps Anything to add/clarify?

**Comment by spencerrecneps** [comment]
@jcahail one additional facility type: off-street paths. These would be identified in the functional_class attribute. These could be colored green.

As for styles, those sound good to me. It might be good to run them past Jennifer to get her clearance (maybe you already did).

**Comment by CloudNiner** [comment]
Depends on #506

**Comment by CloudNiner** [comment]
@spencerrecneps looking at this now. For off-street paths, I only see values of `path` and `living_street` in the `FUNCTIONAL` column of the neighborhood_ways table. Is one of these the value to filter on for this type?

When you state "thicker, darker blue line with a thin dashed white line running down the middle" are you intending that to be used for `track` infrastructure types?

Can you also verify that we should be looking for these infrastructure types in the `FT_BIKE_IN` and `TF_BIKE_IN` columns of the neighborhood ways table?

Does PFB/TDG have specific hex color values we should use for:
- "thinner blue line"
- "thicker darker blue line"
- "thicker darker blue line with thin dashed white line"
Barring having the hex values available, does PFB have a public facing site that demos these styles?

**Comment by spencerrecneps** [comment]
Off-street paths would be `FUNCTIONAL='path'`
Thicker, darker blue line with white dashes would be for `FT/TF_BIKE_IN=track`
Thicker, darker blue line without white dashes would be for `FT/TF_BIKE_IN=buffered_lane`
Thinner blue line would be for `FT/TF_BIKE_IN=lane`

I'll ask Jennifer about map colors. For now let's use these:
* Lighter blue=#009fdf
* Darker blue=#005e83
* Paths=#006b3e

**Comment by CloudNiner** [comment]
@spencerrecneps here's an example that shows all the types mentioned above in a single screenshot. Thoughts?

![screen shot 2017-07-05 at 17 03 23](https://user-images.githubusercontent.com/1818302/27884908-ee7ae7b6-61a3-11e7-9e63-48ba34f18fcf.png)

**Comment by CloudNiner** [comment]
Updated with both FT and TF:

![screen shot 2017-07-05 at 17 13 35](https://user-images.githubusercontent.com/1818302/27885248-50e44ffe-61a5-11e7-9c60-0adf1f53d49e.png)
