### ISSUE TITLE
Add Davis, CA to analysis

### ISSUE THREAD

**Issue by jcahail** [azavea/pfb-network-connectivity#508]
(Awaiting shp file from PFB)

**Comment by jcahail** [comment]
https://drive.google.com/a/azavea.com/file/d/0Bwh7HUe_vpledktwNnlhMHJTRU00ZkFmWHdUbmZUeHRDSDlZ/view?usp=sharing

**Comment by CloudNiner** [comment]
Move file in google drive to fileshare location with other shapefiles

**Comment by KlaasH** [comment]
Merged into #509.
