### ISSUE TITLE
Add Cambridge, MA and Davis, CA to analysis

### ISSUE THREAD

**Issue by jcahail** [azavea/pfb-network-connectivity#509]
(Awaiting shp file from PFB)

**Comment by jcahail** [comment]
https://drive.google.com/open?id=0Bwh7HUe_vpleZkt3YUtiUHhKakNrNG9rTHFTRWVaRTA4VDZR

**Comment by CloudNiner** [comment]
Move file in google drive to fileshare location with other shapefiles

**Comment by KlaasH** [comment]
Merged issue #508 into this.
Davis, CA shapefile: https://drive.google.com/a/azavea.com/file/d/0Bwh7HUe_vpledktwNnlhMHJTRU00ZkFmWHdUbmZUeHRDSDlZ/view?usp=sharing

**Comment by CloudNiner** [comment]
Performed the following actions:
- Downloaded the two above shapefiles
- Copied them to the project/data/production_analysis_shapefiles/ directory on Azavea's internal file host
- Uploaded each shapefile to the production site via the admin interface
- Verified the boundaries are correct by mapping the geojson returned from /api/neighborhoods_bounds_geojson/

<img width="703" alt="screen shot 2017-07-11 at 13 52 22" src="https://user-images.githubusercontent.com/1818302/28082475-9353d220-6640-11e7-81a6-cd8657f611b5.png">
<img width="752" alt="screen shot 2017-07-11 at 13 52 46" src="https://user-images.githubusercontent.com/1818302/28082476-935718ea-6640-11e7-8803-9c12fbb5ad8a.png">

When we re-run by creating a new AnalysisJob for each Neighborhood, these new neighborhoods will be automatically picked up and run.
