### ISSUE TITLE
Paused papertrail account (due to going over log limits) breaks deployments

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#511]
ECS tasks fail to start during deployments with the error:
```
CannotStartContainerError: API error (500): Failed to initialize logging driver: dial tcp 169.46.82.180:32461: getsockopt: connection refused
```

Manually attempts to dial the papertrail endpoint via:
```
telnet logs5.papertrailapp.com <port>
```
also fail with a "connection refused" error. It appears that when your account is paused due to exceeding account limits, new connections are refused by papertrail. Unfortunately, docker treats this as a critical error and refuses to start new tasks.

When the account was upgraded, manual telnet attempts immediately succeeded and the application deployment launched normally.

Two solutions:
1. Keep the papertrail account limits set to a level that won't be exceeded
2. Move to cloudwatch logs

We're currently in contact with PFB in order to pursue option 1.

**Comment by jcahail** [comment]
PFB has agreed to option 1. @hectcastro Should we invite her to the organization (the same way you invited me this morning) and I'll walk her through updating the billing info? Is there a better way to proceed?

**Comment by CloudNiner** [comment]
Here is the related moby issue: https://github.com/moby/moby/issues/21966

**Comment by jcahail** [comment]
Papertrail account payment information has been updated with PFB's credit card.
