### ISSUE TITLE
Change map color ramp

### ISSUE THREAD

**Issue by jcahail** [azavea/pfb-network-connectivity#513]
High stress as red and low stress as dark grey (see below). 
 
PROCESS BLACK 85%
CMYK 0/0/0/85
RGB 72/71/72
HEX 4c4c4e

**Comment by designmatty** [comment]
Honestly, I think switching this to grey is not in the best interest since grey does not equal good when thinking in color theory.  Just my thoughts on the matter.

Since our default basemap is already in greyscale, lets go with a slightly darker/bluish grey to replace the bright blue.
`#4e5c63`

<img width="351" alt="screen shot 2017-07-10 at 10 02 03 am" src="https://user-images.githubusercontent.com/1928955/28021792-1ac66424-6557-11e7-88fa-1091489cc079.png">

**Comment by spencerrecneps** [comment]
@designmatty @jcahail perhaps I misunderstood PFB's intentions, but I thought we were switching red to gray and keeping blue as low stress.

**Comment by CloudNiner** [comment]
I updated the ways layer and the census block color ramp based on values sent by @spencerrecneps, and here's the result (there's almost no visible difference in the ways):

@spencerrecneps @jcahail @designmatty are the new ramps acceptable?

## Before

### Neighborhood Ways

![screen shot 2017-07-12 at 08 52 21](https://user-images.githubusercontent.com/1818302/28118835-ba9264a0-66e0-11e7-923e-9cf68ea34be1.png)
![screen shot 2017-07-12 at 09 00 46](https://user-images.githubusercontent.com/1818302/28118836-ba97521c-66e0-11e7-91dc-50a5ec01bfef.png)

### Census Blocks

![screen shot 2017-07-12 at 08 52 38](https://user-images.githubusercontent.com/1818302/28118851-c6bf7ad8-66e0-11e7-8acf-8cca4f3a56fe.png)
![screen shot 2017-07-12 at 09 00 37](https://user-images.githubusercontent.com/1818302/28118852-c6c111cc-66e0-11e7-9fc0-0a312c26146b.png)

## After

### Neighborhood Ways

![screen shot 2017-07-12 at 09 08 19](https://user-images.githubusercontent.com/1818302/28119117-b1c48e38-66e1-11e7-8c82-42f6803bd0e7.png)

![screen shot 2017-07-12 at 08 58 54](https://user-images.githubusercontent.com/1818302/28118892-f0b5eeb2-66e0-11e7-95d9-741c7da5830f.png)

### Census Blocks

![screen shot 2017-07-12 at 09 08 05](https://user-images.githubusercontent.com/1818302/28119131-b745d0b0-66e1-11e7-9e10-29460e329452.png)
![screen shot 2017-07-12 at 08 58 39](https://user-images.githubusercontent.com/1818302/28118893-f0bb0618-66e0-11e7-88ea-a391ef64a431.png)
