### ISSUE TITLE
Exempt crosswalks from paths style in Bike Infrastructure layer

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#519]
When we added a style to display `FUNCTIONAL='path'` in green, we inadvertently styled what looks like a bunch of crosswalks that are described as paths (example from Germantown, Philadelphia):

![screen shot 2017-07-07 at 14 25 30](https://user-images.githubusercontent.com/1818302/27971347-610eae7a-6320-11e7-80e3-9d72373840b3.png)

This task is to figure out if theres a way to filter these from display on the Bike Infrastructure layer, without compromising the display of actual "paths" on the layer.

**Comment by CloudNiner** [comment]
@spencerrecneps since you're more familiar with the ways file and OSM data, do you have any hunches on how to address this issue?

**Comment by spencerrecneps** [comment]
The crosswalks issue is one I've noticed before. I may have to introduce a new field in the DB to flag them. I'll investigate a fix and hopefully push a commit early next week. Will that work for you?

**Comment by CloudNiner** [comment]
We don't feel strongly about fixing this now if it requires additional flags in the ways file. I was mostly curious to see if you could see a way to address it with the info we currently have available. If not, it seems like it can wait until a later date.

**Comment by spencerrecneps** [comment]
Basically, I pulled in crosswalks in order to ensure that off-street paths are continuous where they cross a street. But I collapsed the crosswalks into the same class as the paths. I'm pretty sure it's an easy fix in the SQL.

**Comment by CloudNiner** [comment]
As long as the implementation doesn't affect other metrics or calculations, that's fine. We wouldn't want a last minute change to jeopardize the second analysis run.

**Comment by spencerrecneps** [comment]
Agreed. I'll just add an additional column with a flag for crosswalks. That should make it easy for you to pull them out without altering anything else.
