### ISSUE TITLE
Update bike infrastructure layer color scheme

### ISSUE THREAD

**Issue by spencerrecneps** [azavea/pfb-network-connectivity#521]
Updated color scheme as follows:

- `FUNCTIONAL='path'` = `#15bf50` -- thinner line (same as bike lane)
- `FT/TF_BIKE_IN=track` = `#44a3a6` -- fattest line (~twice the thickness of bike lane)
- `FT/TF_BIKE_IN=buffered_lane` = `#5072f5` -- fatter line (~1.5 times the thickness of bike lane)
- `FT/TF_BIKE_IN=lane` = `#8c54de` -- thinner line

No dashes or other fancy effects needed on any of the layers.

**Comment by spencerrecneps** [comment]
👍 I felt the dashes caused more visual clutter than anything.

**Comment by CloudNiner** [comment]
@spencerrecneps  here's a visual of what this looks like now:

![screen shot 2017-07-12 at 12 34 26](https://user-images.githubusercontent.com/1818302/28128667-7a0ba4be-66fe-11e7-8b57-b7a24a806860.png)

**Comment by spencerrecneps** [comment]
👍
