### ISSUE TITLE
Compare feature doesn't retain original selection

### ISSUE THREAD

**Issue by jcahail** [azavea/pfb-network-connectivity#523]
After selecting one city (NYC) from the search, I viewed the detail page and chose Compare. 
![image](https://user-images.githubusercontent.com/24727081/28132213-29772fb2-670a-11e7-9a2f-62ea474d3f38.png)

I then chose "Search Places" under "Add a Place to Compare", which takes me back to the search, but doesn't retain my first choice (NYC). 
![image](https://user-images.githubusercontent.com/24727081/28132317-749a8d04-670a-11e7-8933-e9b4d9dc48f1.png)

**Comment by flibbertigibbet** [comment]
Haven't been able to reproduce on staging.

**Comment by rcheetham** [comment]
I observed the same bug. In addition, if a user assembled multiple sites to compare and clicks on any given city (including any of the ones to compare, the compare list is lost.

**Comment by flibbertigibbet** [comment]
Selected places to compare that are not within the paginated list display set are lost on revisiting the list page. (To reproduce, it's necessary to select a place to compare that is not on the current page of the list view, such as with the search function.)
