### ISSUE TITLE
Three additional cities in Arkansas

### ISSUE THREAD

**Issue by spencerrecneps** [azavea/pfb-network-connectivity#524]
Three additional cities in Arkansas to add to the batch for analysis:
1. Rogers
2. Bella Vista
3. Siloam Springs

**Comment by CloudNiner** [comment]
Do you have the shapefiles for these?

**Comment by spencerrecneps** [comment]
I've asked Jennifer for shapefiles by this morning, which might be afternoon for you thanks to the time difference.

**Comment by CloudNiner** [comment]
These neighborhoods were added to the list of neighborhoods for the analysis on the production site:

#### Siloam Springs, AR
<img width="696" alt="screen shot 2017-07-13 at 12 19 29" src="https://user-images.githubusercontent.com/1818302/28176534-d505dfde-67c5-11e7-990b-31566aa1c7b4.png">

#### Rogers, AR
<img width="587" alt="screen shot 2017-07-13 at 12 19 38" src="https://user-images.githubusercontent.com/1818302/28176535-d507a594-67c5-11e7-9baa-98c31cf9cea2.png">

#### Bella Vista, AR
<img width="700" alt="screen shot 2017-07-13 at 12 20 45" src="https://user-images.githubusercontent.com/1818302/28176533-d503c244-67c5-11e7-995f-e4c514e84540.png">
