### ISSUE TITLE
Remove usage of the OSM Overpass API

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#536]
Our large batch runs aren't in the spirit of the good faith limits, and if we trigger jobs in batches, we get throttled, so we know we're not being good stewards.

So, what alternatives do we have?

I only see one strong contender, which is to use [AWS Lambda + Scheduled Events](http://docs.aws.amazon.com/lambda/latest/dg/with-scheduled-events.html) or a similar service to copy the state OSM extracts posted at http://download.geofabrik.de/north-america.html to an S3 bucket in the PFB AWS account on a regular schedule, that keeps them current as the extracts are updated upstream. Then, the analysis job can have some logic added to it that chooses the proper extract based on the state that each analysis is run in.

This project doesn't have the infrastructure, time, or monetary resources to attempt a more ambitious solution such as maintaining custom infrastructure, or downloading the entire world on a regular basis and cutting it ourselves.

Disadvantages to the proposed solution include a dependence on the external site in question, which would be trouble if they stopped releasing the exports. In which case we'd be back to where we started.

**Comment by CloudNiner** [comment]
In the meantime, for the current analysis batch that failed due to Overpass API errors and throttling, I ran the following code in a shell on production to trigger a new set of analysis jobs pointed at the state-level extracts noted above. This seems to be working as a one-off solution.

```python
from datetime import datetime, timedelta

from django.contrib.auth import get_user_model

from pfb_analysis.models import AnalysisJob, AnalysisBatch

import us

# Get approximate start time of analysis
analysis_start = datetime.now() - timedelta(days=4)

# Get total jobs and jobs that failed since analysis_start
AnalysisJob.objects.filter(created_at__gt=analysis_start).count()
AnalysisJob.objects.filter(created_at__gt=analysis_start).filter(status=AnalysisJob.Status.ERROR).count()

User = get_user_model()
user = User.objects.get(email='<account_redacted>')

batch = AnalysisBatch.objects.create(created_by=user, modified_by=user)

for job in AnalysisJob.objects.filter(created_at__gt=analysis_start).filter(status=AnalysisJob.Status.ERROR):
    state_name = us.states.lookup(job.neighborhood.state_abbrev).name.lower().replace(' ', '-')
    # Use state level extracts available at:
    #   http://download.geofabrik.de/north-america.html
    # We have to process the neighborhood state abbrev to a full name in format found in the url
    osm_extract_url = "http://download.geofabrik.de/north-america/us/{}-latest.osm.bz2".format(state_name)
    job = AnalysisJob.objects.create(neighborhood=job.neighborhood,
                                     batch=batch,
                                     osm_extract_url=osm_extract_url,
                                     created_by=user,
                                     modified_by=user)

batch.submit()
```

**Comment by CloudNiner** [comment]
Use of the geofabrik extracts was discussed offline. @ddohler's team used this service in the PRS app and had good results. @lossyrob has spoken with geofabrik before, and the assumption there is that they expect these extracts to be used, so we're most likely ok to use these extracts as a replacement for Overpass. If we were particularly concerned about it, we could send Geofabrik an email describing the app and our expected usage to get a written ok from them. 

@echeipesh and @lossyrob suggested modifications to VectorPipe that would allow us to query that service for extracts, although for now those are in ORC format. We would require additional time and likely a second discussion with them if we decided to move forward with this option.

Pulling the geofabrik NA files is definitely simpler and would be my suggestion for how to proceed. An email to them might be a good-faith way to head off concerns about service longevity and being throttled down the road if PFB kicks off a bunch of jobs all at once.

**Comment by spencerrecneps** [comment]
If I understand your proposal correctly, we'd be building up a whole new infrastructure to download states and keep them current. Is there any reason your solution above to point at the geofabrik state extract for each job at run time is suboptimal as a permanent fix?

In a similar vein, it seems like you could kick off a massive batch run by downloading the whole north american extract and filtering from that for the entire batch. Would that allow us to keep the Overpass API and avoid the good faith limits on batch jobs?

**Comment by CloudNiner** [comment]
If we continue to use your first solution, it fails in the case of large batch runs, where we're paying for additional bandwidth to pull the same file multiple times. For example, if there are ten cities in PA when an entire batch is run, then we're downloading 135mb * 30 cities. It could also lead to a similar situation as Overpass, where we get throttled or blocked for exceeding "good faith" limits on the usage of services (bandwidth is expensive). 

Your second suggestion is untested as to how well the OSM tooling handles clipping very small areas out of very large source files, and the source file is 13GB zipped. Also unclear how this would impact processing times for both large and small jobs. Essentially this option has a very high variability into how well it would perform from a cost, time and implementation perspective. There are quite a few unknowns.

We're still going back and forth a bit on implementation specifics for this, but it won't involve a separate service that requires additional infrastructure or regular maintenance. We'll be posting here with those specifics once they're finalized. Hope this helps understanding.
