### ISSUE TITLE
Remove MN from the analysis results

### ISSUE THREAD

**Issue by jcahail** [azavea/pfb-network-connectivity#541]
Remove the detail page (https://bna.peopleforbikes.org/#/places/d03ec36c-74f2-4627-b26c-cddeed5a7e50/) and remove from search page.

**Comment by CloudNiner** [comment]
After deploying #544 to production, I manually ran:
```python
minneapolis = Neighborhood.objects.get(name__icontains="minneapolis")
minneapolis.visibility = Neighborhood.Visibility.HIDDEN
minneapolis.save()
```
in the production console to remove Minneapolis from the results:

![screen shot 2017-08-08 at 11 15 49](https://user-images.githubusercontent.com/1818302/29079391-152d4fba-7c2b-11e7-8496-ed81229b6506.png)

**Comment by CloudNiner** [comment]
@jcahail @spencerrecneps the other MN neighborhoods are still visible on the site, it looks like Jennifer specifically only requested that Minneapolis be hidden. If we want to hide all the Minnesota neighborhoods we can do that too. Otherwise, this issue is closed.

**Comment by CloudNiner** [comment]
This task is complete. Confirmed with Jennifer that they only want Minneapolis hidden from view.
