### ISSUE TITLE
Re-run the 300+ city analysis (start date: 1/29)

### ISSUE THREAD

**Issue by jcahail** [azavea/pfb-network-connectivity#548]
Using the same shapefiles from the last contract.

**Comment by CloudNiner** [comment]
This ran, but we had to workaround throttling by the Geofabrik OSM state downloads page. This was done by writing a simple python script to loop through all states and push the files to a public S3 bucket. Then each job's `osm_extract_url` was updated to point to the S3 files under our control. Note that Geofabrik's default throttling limits lead to even the python scraper script being throttled before it loops through all 50 states. We'll have to watch out for this when we implement caching.

We also had to re-run the code to manually fix the simplified geoms after batch completion:

https://github.com/azavea/pfb-network-connectivity/issues/452#issuecomment-303112082
