### ISSUE TITLE
Run the additional 200 cities once the initial 300+ city re-run is mostly complete

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#549]
Blocked by #548 

Send Spencer the shapefile format necessary for our importer.

**Comment by jcahail** [comment]
Kick off when 300+ city analysis is 85% OR by Feb 16, whichever is sooner.

**Comment by CloudNiner** [comment]
This ran successfully with out issue. The only errors were in Alaska and Puerto Rico. 

#423 addresses the Alaska failures

#550 addresses the Puerto Rico failures
