### ISSUE TITLE
Run large city

### ISSUE THREAD

**Issue by KlaasH** [azavea/pfb-network-connectivity#57]
Get disk usage over time

**Comment by CloudNiner** [comment]
The analysis job I started for all of philadelphia county (24500 blocks) ran the parallelized high stress connectivity sql in 20hrs, and the parallelized low stress connectivity sql in ~12hrs. Then connected_census_blocks.sql crashed one minute in with a disk space error. The analysis used ~35Gb up to that point.

Resized VM disk to 200Gb following instructions here, steps 1-8: https://gist.github.com/christopher-hopper/9755310

**Comment by CloudNiner** [comment]
I was able to successfully run Philadelphia county. Total run time was ~70hrs using ~50Gb of disk space. 

Detailed notes:
```
Total Time: ~70hr to run full analysis, not including data import time, which is < 15min
- building_graph: 5min
- reachable_roads_high_stress: 10hr, cleanup: 12min
- reachable_roads_low_stress: 9hr, cleanup: 1min
- connected_census_blocks: 48hr
- misc metrics: 20min
- connected_census_block_schools: 1hr, 16min
- remaining metrics: negligible

Disk usage: ~50Gb

Other adjustments:
Temp tables used by connected_census_blocks.sql explode disk usage due to swapping unless postgresql.conf `work_mem` is set much higher. Phila county ran successfully with `work_mem` set to 4096Mb.
```

Screenshot for proof:
![screen shot 2017-02-15 at 11 30 46](https://cloud.githubusercontent.com/assets/1818302/22984119/688d68bc-f372-11e6-846e-36b03a337d6d.png)

**Comment by CloudNiner** [comment]
Following up, I exported the data for this run using the new `export_connectivity.sh` script. Total data is 2Gb unzipped for neighborhood_ways.shp, neighborhood_connected_census_blocks.shp and overall_scores.csv. Most of that is the DBF for neighborhod_connected_census_blocks at 1.9Gb. 

Zipped files will be on fileshare in the data folder.
