### ISSUE TITLE
Jobs list: status filter uses short name but list shows long name

### ISSUE THREAD

**Issue by KlaasH** [azavea/pfb-network-connectivity#576]
In the status filter on the Analysis Jobs admin view, the values suggested by the autocomplete and used for filtering are the "short" labels from [the JOB_STATUSES object](https://github.com/azavea/pfb-network-connectivity/blob/develop/src/angularjs/src/app/analysis-jobs/analysis-jobs.constants.js) but the "long" labels are shown in the list.  So for example if I see "Calculating Connectivity" in the list and start typing "calc", no autocomplete suggestion will come up.  Nor will copying "Calculating Connectivity" into the box, since it doesn't match what the filter is looking for.

**Comment by jcahail** [comment]
Closed in #573.
