### ISSUE TITLE
Analysis job does not progress past Created phase

### ISSUE THREAD

**Issue by beckymasond** [azavea/pfb-network-connectivity#584]
**Issue**: When running the analysis via the admin interface, the analysis does not progress past the CREATED stage. 

**Reproduction steps**: 
1. Start instance via AWS Auto Scaling Groups page.
2. Navigate to [Analysis Jobs ](https://bna.peopleforbikes.org/#/admin/analysis-jobs/) on BNA admin website.
3. Click 'Run Analysis.'
4. Select any existing geography for neighborhood. I used **denver_region4**, which is set to private.
5. Click 'Submit Analysis Job.'

**Expected outcome**: Analysis runs through phases to completion.
**Actual outcome**:
- Red error message appears in upper right corner that says "Error submitting analysis job: [object Object]"
- Job appears in Analysis Jobs list but does not progress past "Created" phase when allowed to run 12+ hours for a small region.

**Comment by CloudNiner** [comment]
The test `denver_region4` job has completed and can be found in the admin console. @beckymasond , you should be able to run jobs again from the admin interface.

**Comment by beckymasond** [comment]
Verified -- the analysis ran successfully for me. Thanks!
