### ISSUE TITLE
Review and merge residential speed PR

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#588]
#585 

We should:
- [ ] ensure no regressions on performance of jobs
- [ ] ensure no issues with job outputs

**Comment by flibbertigibbet** [comment]
Here are my notes on #585:

- should change data type of added FIPS code references everywhere passed and used to char types (not numeric, as they are now); it works, but such an identifier should be stored as a string
- need to also update `README.LOCAL-ANALYSIS.md` to:
  - note added city FIPS env var
  - note that it is for 2010, consists of state + local place FIPS concatenated, and can be found at:
   https://www2.census.gov/geo/docs/reference/codes/files/national_places.txt
  - update the notes for each place in the doc to add the appropriate local FIPS
- need to add city FIPS to neighborhood model and pass it to analysis run, also print it for local command env var
- fix spacing: added shell files should have four spaces, not two, for consistency with existing analysis shell files
- check for local versions of added files for city and state default speeds before downloading
  - will this mean staging/prod won't pull updated versions from S3?

I ran the analysis for lower Manhattan locally, and compared to a baseline run for the same area, the overall scores are the same. The second run, with the default city speed set and water Census blocks removed, took about 4.5 hours. Removing the blocks seems to be a relatively quick operation, and may reduce the overall processing time with the area covered.

Baseline run on the left, run with changes on the right:

![pfb_lh_old_left_new_right](https://user-images.githubusercontent.com/960264/49235605-76fb7580-f3c8-11e8-821f-1714af22ec27.png)


![pfb_lm_census_old_left_new_right](https://user-images.githubusercontent.com/960264/49235608-79f66600-f3c8-11e8-80b0-094c1ca9b496.png)

To be able to test with a default city speed set, it was necessary to override the default city speed file from S3, which only has a few entries. (The state speed file seems to have them all.) However, I'm not sure if adding a guard block to test for a local copy first in `/data` would then mean updated versions would not get pulled from S3 in staging or production.

**Comment by flibbertigibbet** [comment]
Created #608 for the Django model changes needed to support the analysis change.
