### ISSUE TITLE
Set up remote development Tilegarden endpoint using Staging database

### ISSUE THREAD

**Issue by KlaasH** [azavea/pfb-network-connectivity#593]
We need to be able to test the tiler running in the actual AWS environment but without having to merge to develop and deploy staging.  So we need to be able to run a remote development Tilegarden endpoint, pointed at the Staging database.  (It might still be limiting to not be able to test database schema changes remotely in development, but that would be much harder to accomplish.)

**Comment by hectcastro** [comment]
In Raster Foundry, we use the `test/` branch prefix to trigger automatic deployments to staging. That allows us to more easily test things in staging without having to merge into `develop`. Afterwards, re-triggering a `develop` build wipes the `test/` branch contents away.

**Comment by KlaasH** [comment]
Looking at this again, that "build `test/` branches" strategy sounds pretty good.  Would that just be a matter of changing [the Jenkinsfile](https://github.com/azavea/pfb-network-connectivity/blob/0.8.1/Jenkinsfile#L32) and adding `test*` to the "Include" filter under "Filter by name (with wildcards)" in the repo configuration on Jenkins?

**Comment by hectcastro** [comment]
Yeah, roughly https://github.com/raster-foundry/raster-foundry/commit/bb787d09a2a5d1fad0d3094b071df013d499721b and the Jenkins org (you can't tweak settings for individual repos) configuration change to inculde `test/*`.
