### ISSUE TITLE
Load and benchmark AnalysisJob geometries on staging

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#602]
#600 added a migration and a management command which can be used to copy all AnalysisJob shapefiles into PostGIS in the main DB. 

This task is to run that management command on staging. We should be wary of cpu, memory and DB disk constraints for larger analysis jobs. Any insight gained should be added as new issues to address before running the same commands on production.

It's probably worth kicking off a larger area, such as Philly, one of the NY boroughs or even Dallas or LA. Note that these jobs take up to a day or so to run on our staging resources.

Depends on #601

**Comment by flibbertigibbet** [comment]
The 62 completed jobs on staging were re-imported successfully in 50 minutes, run via an ECS command (in order to get logging output in Papertrail).

RDS metrics:
![image](https://user-images.githubusercontent.com/960264/49828609-5503da80-fd5a-11e8-97f8-94d8b73abfc6.png)

**Comment by flibbertigibbet** [comment]
ECS CloudWatch metrics:
![image](https://user-images.githubusercontent.com/960264/49829122-9648ba00-fd5b-11e8-9d71-c7fade5af810.png)

**Comment by CloudNiner** [comment]
Nice. Looking at that it appears we maxed out at about 30IOPS/s. According to the table here: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html our baseline IOPS performance at just over a 120Gb RDS volume is 300IOPS, so we should be good there. 

It doesn't look like we used a significant amount of CPU credits, no imports took more than a few minutes and we barely put a dent in the available 120Gb of database storage we already have provisioned. 

Do you feel confident in progressing from here to running the import script as is without further benchmarking or are there things you would prefer to still test?

**Comment by flibbertigibbet** [comment]
Based on this run, I think we should be fine to go ahead and run the import on production.

**Comment by CloudNiner** [comment]
👍 sounds good.
