### ISSUE TITLE
Remove old tiling container, code, and config

### ISSUE THREAD

**Issue by KlaasH** [azavea/pfb-network-connectivity#611]
Including:
- The `tilemaker` container and source tree
- The related code and settings in the Django app
- Related infrastructure configuration (e.g. the `tilemaker` SQS queues and job definitions)

Requires #650

**Comment by KlaasH** [comment]
Also need to make sure the analysis job ends with `COMPLETE` status, since it currently puts the job in `EXPORTED` status when it's done and it's the `tilemaker` container that [marks it Complete](https://github.com/azavea/pfb-network-connectivity/blob/d6ffcd6cc1b186171981852a7a62e68c4e9f82c0/src/tilemaker/entrypoint.sh#L26).

**Comment by flibbertigibbet** [comment]
Connects #650

**Comment by flibbertigibbet** [comment]
Also remove the tiler toggle logic from #650.
