### ISSUE TITLE
Imported census block results geometries include the buffer area as all zero

### ISSUE THREAD

**Issue by KlaasH** [azavea/pfb-network-connectivity#612]
The tiles generated from the imported census block scores all have a big red boundary around the neighborhood being analyzed.  E.g.:

![image](https://user-images.githubusercontent.com/6598836/49449801-b00d5e80-f7a9-11e8-8e93-a6fa8d3b7e7c.png)

The same neighborhood on the production site shows:
![image](https://user-images.githubusercontent.com/6598836/49449830-c2879800-f7a9-11e8-8ddc-45b0240f651a.png)

I initially thought that must be something in the shapefile that we were formerly throwing away when tiling, but I don't see anything in [the `tilemaker` script](https://github.com/azavea/pfb-network-connectivity/blob/0.7.0/src/tilemaker/scripts/run_tilemaker.sh#L58-L62) that would have that effect.  So now I'm wondering if there's a distinction between 0 and "no score" in the shapefiles that "just worked" for tilemaker but isn't working how we want for the geometry import.

The "ways" results also extend outside the boundary to the edge of the buffer, but that's fine because the scores are still correct in the buffer area (I compared Germantown to Philadelphia and they were the same).

**Comment by flibbertigibbet** [comment]
Lower Manhattan, without all-water Census blocks removed:

![image](https://user-images.githubusercontent.com/960264/49461632-1a31fd80-f7c2-11e8-8f8e-f94fd2ebb650.png)


Lower Manhattan, with water Census blocks removed (#585):

![image](https://user-images.githubusercontent.com/960264/49461675-40f03400-f7c2-11e8-9ebd-b32f27db80b6.png)

**Comment by flibbertigibbet** [comment]
On further investigation, the issue seems to be that the new map styles erroneously include zeroes in the same bin as the smallest non-zero values, where the old style smallest bin excluded zeroes.

**Comment by KlaasH** [comment]
I read that Esri link as saying that shapefiles _do_ support nulls and talking about how to handle that when converting to Esri's "coverage" format.

But yeah, `LayerMapping` is not observing that distinction, nor does there seem to be any way to tell it to do so.

**Comment by flibbertigibbet** [comment]
[Here](http://resources.esri.com/help/9.3/ArcGISDesktop/com/Gp_ToolRef/geoprocessing_tool_reference/geoprocessing_considerations_for_shapefile_output.htm) is some further documentation from ESRI on how nulls are not supported in Shapefiles.

(see "When should I not use a shapefile?")

**Comment by flibbertigibbet** [comment]
It looks like support for recognizing nulls was [added to OGR](https://trac.osgeo.org/gdal/wiki/rfc67_nullfieldvalues) in GDAL version 2.2; our system package is on 2.1. As Mapnik also uses OGR and looks like it's on the same base image, it's unclear what the difference would be in treatment.
