### ISSUE TITLE
Update Tilegarden CloudFront CNAME in Terraform to reference a FQDN 

### ISSUE THREAD

**Issue by jeancochrane** [azavea/pfb-network-connectivity#659]
The `aliases` attribute in the CloudFront configuration for Tilegarden generates a CNAME for the distribution by modifying the name of the Route53 public hosted zone:

https://github.com/azavea/pfb-network-connectivity/blob/dcee6c27afb28992955a27f6da611d0c9b1beed5/deployment/terraform/cdn.tf#L20

Our public hosted zones end in periods (e.g. `bna.peopleforbikes.org.`), which means they are not valid FQDNs, so Terraform errors when you try to create the distribution.

I'm not sure why this worked when we set up the staging instance of Tilegarden (or, for that matter, why Terraform hasn't attempted to change the CNAME for the staging distribution, since we confirmed that the staging hosted zone name also ends in a period). We need to get to the bottom of this discrepancy and fix the `aliases` attribute so that production deployments can continue.

**Comment by rbreslow** [comment]
I modified the remote state to drop the period, and I updated the `terraform.tfvars` file to drop the period. 

Terraform plan/apply cycles cleanly now. 

I think the problem is that we had `var.r53_public_hosted_zone` set to `bna.peopleforbikes.org.`.
