### ISSUE TITLE
Add new BNA logo

### ISSUE THREAD

**Issue by jcahail** [azavea/pfb-network-connectivity#668]
Forthcoming.

**Comment by jcahail** [comment]
Logo:https://drive.google.com/file/d/0Bwh7HUe_vplebVVOZWlfZWk5OWZyRGpCRlhHaWQ1azZ2WHJj/view?usp=sharing

Secondary logo (to use only if there are spacing issues): https://drive.google.com/file/d/0Bwh7HUe_vpleb3RKcjZIYnBpQUtaZ1EwZXlmWFZ4S0Rta0Nz/view?usp=sharing

Full color version for reference only: https://drive.google.com/file/d/0Bwh7HUe_vpleZmZVdG5GVUtPWS1rbUxHNkszbmFFUjMtY2xv/view?usp=sharing

**Comment by KlaasH** [comment]
The site currently uses the PFB logo
- As a large icon in the middle of the home page
- As a smallish icon in the nav bar on the home page
- As a logo (icon and name) in the nav bar on the Places view
- As a logo in the footer on the home page

The new logo works fine in the middle of the home page, and my understanding is that the footer should keep the PFB logo, but the smaller version of the new logo isn't an icon, just a slightly condensed logo, and the small text makes it not really work as a replacement for the icon in the nav bar.

Here's a screenshot:
![image](https://user-images.githubusercontent.com/6598836/52575588-6fa31000-2dec-11e9-8398-6e42f2feab95.png)

I pushed [a branch (feature/kjh/bna-logo)](https://github.com/azavea/pfb-network-connectivity/tree/feature/kjh/bna-logo) with these changes.

@beckymasond how should we proceed?

**Comment by beckymasond** [comment]
I'll touch base with my team to get their thoughts and follow up by end of day today or early tomorrow.

**Comment by beckymasond** [comment]
* As a large icon in the middle of the home page: We'd like to remove the first line of text "PlacesForBikes..." below the logo. Seeing this logo in place on the background, it looks busy. Could we use the simpler logo from the upper left corner and set that as the main logo, made somewhat larger than the current one?
* As a smallish icon in the nav bar on the home page: Our graphic designer is working on a modification to this and aims to have it done by EOD Thursday, if that works for your timeline.
* As a logo (icon and name) in the nav bar on the Places view: Same as previous.
* As a logo in the footer on the home page: Correct - we'd like to leave this as the PFB logo that links back to the main webpage, peopleforbikes.org.

**Comment by beckymasond** [comment]
Attached is a revised, smaller version of the logo for the upper left corner. If you need any clarification of my prior comments please let me know.

![bna_logo_pfb_lockup-01](https://user-images.githubusercontent.com/13860074/52870320-cf5b2d00-3104-11e9-9004-63e5e5090023.png)
![bna_logo_pfb_lockup-02](https://user-images.githubusercontent.com/13860074/52870321-cf5b2d00-3104-11e9-9183-c0d306accc63.png)
