### ISSUE TITLE
Upgrade countries endpoint to provide state/province information

### ISSUE THREAD

**Issue by KlaasH** [azavea/pfb-network-connectivity#731]
- Use `pycountry` rather than `django-countries`, since it includes state/province information
- Add country config to settings.py to control which countries we want states for
    - This will also be where we put label customization, so a dictionary by country probably makes sense, rather than just a list.
    - People For Bikes will provide this information along with the label customization 
- Since the front-end will need to dynamically adjust the state/province filter by country, it might make sense to just return all country and state/province information in a single response.  It would be cacheable, and if it's not prohibitively large would save the extra work of doing additional API calls to get state/province information per country.

**Comment by flibbertigibbet** [comment]
There's also [django-cities](https://github.com/coderholic/django-cities), which uses GeoNames.
