### ISSUE TITLE
Update docker and terraform versions

### ISSUE THREAD

**Issue by KlaasH** [azavea/pfb-network-connectivity#760]
Per @flibbertigibbet on PR #759:
> I noticed some deployment dependencies and roles could use updating, in group_vars/all.example (docker_compose_version and terraform_version, and probably docker_version as well, it's not clear to me what version ECS should be on from [this](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container_agent_versions.html)) and in roles.yml (terraform and docker).

The `docker_version` should match the version in the AMI we're using, which means I should have changed it when I changed the AMI for [issue #579](https://github.com/azavea/pfb-network-connectivity/issues/579).  I doubt there's a whole lot of risk arising from having them not match, but it makes sense to align the development and deployed environments as closely as we can.

**Comment by BryanQuigley** [comment]
The docker part of this was fixed as part of #856.
