### ISSUE TITLE
Export neighborhood_ways as geojson in export_connectivity.sh

### ISSUE THREAD

**Issue by KlaasH** [azavea/pfb-network-connectivity#78]
_Moved from https://github.com/azavea/pfb/issues/16, created by @CloudNiner on 2/6/17_

Easiest way to do this is with `ogr2ogr`, but installing via the `gdal-bin` package provided by the ubuntugis PPA leads to a dependency conflict with the `postgresql-9.6-postgis-2.3` package, where `gdal-bin` expects `libgdal2` and `postgresql-9.6-postgis-2.3` expects `libgdal1h`. 

This would resolve nicely if the analysis and postgresql service were two different containers. Otherwise it might be best to install the gdal tools from source?

**Comment by CloudNiner** [comment]
No longer necessary, and the blocker where we were unable to install gdal-bin was resolved.
