### ISSUE TITLE
Create new TLS certificate and apply it via Terraform

### ISSUE THREAD

**Issue by hectcastro** [azavea/pfb-network-connectivity#797]
It appears as though the current TLS certificate for `bna.peopleforbikes.org` is setup to be validated via email. To help minimize the need for manual intervention, we should create an identical replacement certificate via ACM and apply it via Terraform. Once the new certificate is applied, the old one can be deleted.

**Comment by rbreslow** [comment]
- I created a new, DNS validated ACM certificate
- I updated the CloudFront distribution and HTTPS ALB listener via the AWS Console
- I did a find and replace operation on the `state` file from the old ARN to the new ARN
- I updated the `ssl_certificate_arn` variable for the production `.tfvars` file
- I ran `./scripts/infra plan` and confirmed that the plan is up-to-date
