### ISSUE TITLE
Upgrade Node runtime for tilegarden

### ISSUE THREAD

**Issue by KlaasH** [azavea/pfb-network-connectivity#801]
A staging deploy failed with "InvalidParameterValueException: The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions."

The existing production tiler is working fine.  I skipped that part of the deployment last time, since there were no changes, and we could presumably do that again if necessary.  Until either we want to change something or something else happens that requires a full redeploy.  Best to be ready.

I don't think there's any reason to expect problems upgrading the runtime, though we'll also want to upgrade dependencies, which means there could be trouble from `node-mapnik`.

**Comment by flibbertigibbet** [comment]
Someone else tried updating a Lambda for node 10/12 with `node-mapnik` and wound up using a custom executable: https://github.com/mapnik/node-mapnik/issues/937
