### ISSUE TITLE
Add default speed limit information to analysis results and show in front-end

### ISSUE THREAD

**Issue by KlaasH** [azavea/pfb-network-connectivity#804]
The analysis knows the default speed limit--either from a city-specific one or from the state-level defaults--and uses it for stress calculations.
We want to display that information to the user when they're looking at a neighborhood's scores etc, so we need to
1. export it into the analysis results files
2. import it into the AnalysisJob model (it doesn't really belong with `overall_scores`, so probably it makes sense as a new field)
3. display it in the front-end.  I don't think there's a design for this, but I believe there was discussion about showing it in a corner of the map.

**Comment by KlaasH** [comment]
There was some discussion of the design for this, and some back-and-forth with PFB. The two big questions were "sidebar, map, or both" and how to handle units (e.g. hard-code by country, provide a toggle, just show both).  The conclusion, [described in the Slack channel](https://azavea.slack.com/archives/C2EA8GZ7T/p1603289643035500), takes the simpler road on both questions:
- Only display the speed limit on the map, not in the sidebar
- Move the graphic so that it's stacked with the legend on the map
- Keep the graphic's navy color regardless of the stress level
- Show both miles and kilometers on the graphic for all places
- Spell out the word "residential" in place of the abbreviation

![wireframe](https://user-images.githubusercontent.com/6598836/97309961-1174c580-1839-11eb-8329-e4c634035f49.png)

Some notes and further questions:
- I was misreading the analysis code and overestimating how often we have a default speed limit.  In [speed_limit.sql](https://github.com/azavea/pfb-network-connectivity/blob/develop/src/analysis/features/speed_limit.sql) we pull speed limit info from OSM, but that's for individual segments. The only place we get a default residential speed limit is in [import_osm.sh](https://github.com/azavea/pfb-network-connectivity/blob/0.13.0/src/analysis/import/import_osm.sh#L150-L211), where we load it from the state and local CSV files.
- So I don't think there's a way to set a default speed for a non-US city.  Unless Rebecca is doing a workaround like assigning a pseudo-FIPS code and using a local speed limits file that has a row matching it.
- This definitely means we need to make sure the box only shows up when there's a value available.
- Since the speeds are all in MPH, we'll need convert and round to get KPH speed limits. I think it makes sense to do that in the front-end.
- But if there's not in fact a way to set a default for non-US cities, that might affect whether it's worth showing KPH at all.

@stephwall @designmatty

**Comment by KlaasH** [comment]
Re my first note above: looking at the [`state_fips_speed.csv` file](https://github.com/azavea/pfb-network-connectivity/files/5447809/state_fips_speed.txt) on S3 answers my question about whether/how we're providing default speed limits for non-US places. It includes rows for the Canadian provinces plus the 2-letter country codes for France, Norway, and Belgium.  Though the numbers appear to be in km/h, which is another issue, since the analysis is assuming mph.

**Comment by kevinearldenny** [comment]
@KlaasH From my review of the analysis code, I was under the impression that all speed limits defaulted to 25 mph if a default speed limit was not explicitly specified ([here](https://github.com/azavea/pfb-network-connectivity/blob/2fc3cb7f1ae9d7c6810bedadb257692fdb581462/src/analysis/stress/stress_segments_lower_order.sql#L18) and [here](https://github.com/azavea/pfb-network-connectivity/blob/d8b5202e83e9d5d30c6f82508dc4b3bf3fd4f110/src/analysis/stress/stress_segments_higher_order.sql#L56))

If there is an implicit default of 25 mph being set, does it not make sense to have that displayed on the frontend? 

On a separate note - it's very odd that the KMH speed limits are being ingested in their raw form and not converted to MPH. Does this have any effect on the validity of the analysis for non-US neighborhoods?

**Comment by stephwall** [comment]
I reached out to PFB about the km/h analysis issue. I'll follow up when I hear back from them.

**Comment by KlaasH** [comment]
From Rebecca:
> Yes, that's true, those are km/h values for nearly every non-U.S. place. I have a copy of the analysis I run locally that processes speeds in metric, along with some other adjustments for international locations. A workaround I could implement is to use my own local state speed file when I run international cities, and then keep the AWS version fully in mph. Would that be a useful solution?
It also sounds like this state speed file needs to contain a speed for every state, province, and country if it is to appear accurately. Is that right? We might run out of two-digit numbers in that case. Would there be any problem with adding three-digit FIPS numbers to this file specifically for this purpose? And would it be best for me to add a column with country and province names for identification purposes? I'm thinking the list could get long over time, so I want to make sure I'm handling that potential growth appropriately.

**Comment by KlaasH** [comment]
The big things we need to do for this are:
1. Store the default speed limit in the analysis exports and load it into the app.
2. Display it on the map.

Each of those has, as it turns out, a number of snags and nuances.

The solution currently up in PR #807 pushes the default speed limit to the Django app to be added to the job instance, but it doesn't store it in the exported files.  Because of the requirement to be able to run the analysis locally and import the results, the `AnalysisJob` instances are a bit of an odd bird in this app--they have most of the information from the analysis run and some additional metadata, but in some ways the exported files on S3 are actually the canonical source for the results.  So as we're currently doing with `overall_score`, it makes sense to push the speed limit value to the model instance when running the analysis on Batch, but we also need a way to get it out of the exported files and save it onto the instance when importing.

Possibly the simplest way to do that would be to create a whole new table and output file (similar to `neighborhood_overall_scores`/`neighborhood_overall_scores.csv` but with just one row) just to store the default speed limit.  Or it might make sense to add it to `neighborhood_score_inputs`.  But a new table might be the way to go, since I don't think those two exist at the point where we're getting the default speed limit.  In any case, we'll need the analysis export to write it out one way or another, and the app import process to pull it out and save it to the instance.

The existence of a modified-for-metric version of the analysis is interesting, and makes the metric speed limit values make sense.  But I don't think it makes sense to try to make the speed limit logic in the tracked version of the analysis unit-aware if the rest of it isn't.  So I would advocate for keeping the value exported by the analysis and used in the app in MPH.

For the front-end, it seems like we're pretty close.  We'll have a box on the map that shows the speed in both units, with it stored in MPH and converted dynamically.

#### Related questions
**Jobs without default speed limits**
Do we expect every analysis to have a default residential speed limit? If not we'll need to make sure the analysis export and app import fail gracefully.

In either case, we need the front-end to fail gracefully, since existing analysis jobs don't have the speed limit. That seems straightforward--just don't show the box.

**Speed limits file**
The `state_fips_speed.csv` and `city_fips_speed.csv` files are an OK solution, but not necessarily one we should build too much on top of.  Extending `state_fips_speed.csv` with fake codes to supply default limits for other countries and provinces seems fine in the current setup where the analysis run on AWS only uses the state ones and the pseudo-FIPS are only used in the locally-modified analysis.  In that case the extra lines can be in whatever units the local code expects, and it's up to the local analysis to export in MPH.  And I don't think there's any reason to think 3-digit numbers wouldn't work.

If we were trying to do more--e.g. make the analysis unit-aware or support non-US cities more fully--I think we should change the way that information is stored.

**Comment by KlaasH** [comment]
> From my review of the analysis code, I was under the impression that all speed limits defaulted to 25 mph if a default speed limit was not explicitly specified

Those are SQL scripts, so the single-`=` are equality checks.  The `COALESCE(speed_limit,:default_speed)` means it'll use a speed limit that came with the OSM segment or fall back to `default_speed`.  For most of the `stress_segments` files, `default_speed` is hard-coded in `import_osm.sh`, so it'll always be there.  And in fact, now that I look at it more closely, in [stress_segments_lower_order_res.sql](https://github.com/azavea/pfb-network-connectivity/blob/0.13.0/src/analysis/stress/stress_segments_lower_order_res.sql#L18) where the city and state defaults are used, it's an error if they're missing.  So I guess that answers the question about analysis jobs with no default speed limits--there shouldn't be any.
