### ISSUE TITLE
Rename nb_boundary_buffer environment variable

### ISSUE THREAD

**Issue by spencerrecneps** [azavea/pfb-network-connectivity#81]
The name nb_boundary_buffer is a little misleading. I suggest renaming to something like max_travel_distance. In some cases we use the value as a buffer on the neighborhood but it's really just an assumption about the maximum travel distance we want to allow.

**Comment by CloudNiner** [comment]
rename to `NB_MAX_TRAVEL_DISTANCE` and adjust the parameter value accordingly.

**Comment by KlaasH** [comment]
See https://github.com/azavea/pfb-network-connectivity/pull/119#discussion_r104037827.  We should truncate the census blocks table to half the max travel distance.
