### ISSUE TITLE
Upgrade Postgresql in development and staging

### ISSUE THREAD

**Issue by ddohler** [azavea/pfb-network-connectivity#859]
AWS is end-of-life-ing Postgresql 9.6, and will forcibly upgrade us to version 12 after ~January 18th~ April 26th.

Further details: https://forums.aws.amazon.com/ann.jspa?annID=8499

**Comment by KlaasH** [comment]
Per discussion in RRP, I changed this from a "do the whole thing" task to a "development and staging" one.  So the pieces are:
- Upgrade the dev environment
- Test in development and make any necessary code or configuration changes. Hopefully the code is fine. This is all a bit simpler if we just need to upgrade RDS and don't need a code deploy.
- Draft a checklist for upgrading the staging RDS instance
- Follow the checklist to upgrade staging.
   Note: If there are code changes needed, push a test branch to get them deployed to staging (or do it manually, but that's more work and I'm not sure there'd be any advantage to it).

So the outcome of this task should be that development and staging are fully upgraded and we have a checklist to follow for upgrading production.

**Comment by BryanQuigley** [comment]
Jenkins does not run this using Vagrant - which means we need to either upgrade Jenkins or migrate this to GH actions.  Happy to run with migrate to GH actions.
