### ISSUE TITLE
Upgrade Postgres on production

### ISSUE THREAD

**Issue by KlaasH** [azavea/pfb-network-connectivity#860]
The second issue of the upgrade. Issue #859 should result in detailed instructions for how to upgrade production (and whether or not doing so requires a code deploy).

**Comment by BryanQuigley** [comment]
- [ ] Upgrade bastion
 - [ ] Switch to t3 instance type (5 minutes)
 - [ ] ALTER EXTENSION postgis UPDATE TO "2.5.5"; (run twice then log back in to confirm)
 - [ ] Update database from  9.6.23->12.8 (<30) - use default parameter group
 - [ ] SELECT PostGIS_Extensions_Upgrade(); to get to 3.1.4 (run twice then log back in to confirm)
 - [ ] Update database from 12.8->13.6 (<20) - use default parameter group
 - [ ] SELECT PostGIS_Extensions_Upgrade(); to get to 3.1.5 (run twice then log back in to confirm)
 - [ ] \timing then VACUUM (FULL, ANALYZE, VERBOSE); 
 - [ ] Update terraform variables to match and show no rds changes

Check commands to run before doing a long operation:
SELECT * FROM pg_available_extensions WHERE installed_version IS NOT NULL;
SELECT * FROM pg_available_extension_versions WHERE name in ('postgis', 'plpgsql');
\l+ (database sizes)

Testing VACUUM FULL went from 694 MB to 500 MB in .5 minutes.

Items to confirm before production deploy:
 * Is t3.small fine or should we go with t3.medium (memory usage seems fine)?
 * Drop MultiAZ to speed up upgrade process (and leave it off?)

**Comment by BryanQuigley** [comment]
Vaccum
42 GB -> 32 GB

INFO:  "django_content_type": scanned 1 of 1 pages, containing 22 live rows and 0 dead rows; 22 rows in sample, 22 estimated total rows
VACUUM
Time: 3206160.835 ms (53:26.161)

Note to my future self - put "Items to confirm before production deploy:" before a bunch of instructions...
