### ISSUE TITLE
Change header links

### ISSUE THREAD

**Issue by KlaasH** [azavea/pfb-network-connectivity#864]
PFB would like to make the following changes to the header navigation bar links:
- Methodology: Link to a yet-to-be-determined URL on the City Ratings site, which will be provided by the start of Q2 of this year.
- Feedback: Rename the button “City Ratings” and link to the City Ratings homepage (http://cityratings.peopleforbikes.org/).

**Comment by jacobscarfmerrell** [comment]
@KlaasH Mind if I take this? I'm guessing Methodology should be linked to this page: https://cityratings.peopleforbikes.org/how-city-ratings-works

**Comment by stephwall** [comment]
They'd like us to link to this page:  https://cityratings.peopleforbikes.org/about/methodology

**Comment by jacobscarfmerrell** [comment]
@stephwall Should I wait to update the link and merge this until they have something at that route besides a 404 page?

**Comment by stephwall** [comment]
Yeah, let's hold off on this until the link is ready.
