### ISSUE TITLE
Upgrade Django to 3.2

### ISSUE THREAD

**Issue by KlaasH** [azavea/pfb-network-connectivity#877]
2.2 is reaching the end of its support window.  Time to hop onto the next long term support release.

Note: this should be done either after or in conjunction with issue #876, since the old Python version in the analysis container will mean that any major updates to the Django requirements (which it installs, to be able to run management commands) will cause it to break.

**Comment by ktohalloran** [comment]
Closed by [PR 893](https://github.com/azavea/pfb-network-connectivity/pull/893).
