### ISSUE TITLE
Add API endpoint in Django to trigger an analysis job

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#93]

**Comment by CloudNiner** [comment]
Depends on #99 and #55

**Comment by CloudNiner** [comment]
Since it should be relatively trivial, include endpoint for GET /api/analysis-job/

**Comment by flibbertigibbet** [comment]
Also depends on #119

**Comment by CloudNiner** [comment]
Actually, this should be fine, since all of the modification in #121 is contained within the `AnalysisJob.run()` method which is all this task should be concerned about calling. But, it may not hurt to wait since there may be other non-obvious concerns.

Since we'll be triggering jobs in AWS, #119 shouldn't apply.
