### ISSUE TITLE
Write python script to trigger many analysis jobs at once

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#98]
We're receiving the final list of cities and their input neighborhoods from data analytics. We should chat with whoever is doing the work to settle on an input format for the data so that this script can efficiently read it and trigger new jobs.

Once this task is done we should be able to start trial runs of the 300 cities deliverable.

**Comment by CloudNiner** [comment]
Depends on #91, #96, #100

**Comment by CloudNiner** [comment]
As per a discussion with Esther and Dan, the input to this script will be a single shapefile, where each neighborhood to run is a polygon in that file. The neighborhood name and 2-letter state abbreviation will be attributes on each polygon.

**Comment by dmcglone** [comment]
Sample shapefile for three cities:

[pfb_city_boundaries.zip](https://github.com/azavea/pfb-network-connectivity/files/845891/pfb_city_boundaries.zip)
Projection: WGS 1984, SRID: 4326

**Comment by CloudNiner** [comment]
Awesome, looks great. Thanks for putting this together.

**Comment by CloudNiner** [comment]
@dmcglone @eneedham we may have to add an additional attribute to some of the polygons in the shapefile, which would be a public URL to retrieve the appropriate OSM data from. Some larger boundaries cannot have the necessary OSM data retrieved automatically due to Overpass API limitations. We'll be creating a fix in #176, so check back in before creating the shapefile with the full list of cities.

**Comment by dmcglone** [comment]
Would this be a unique attribute per city? We could potentially add extent coordinates of each polygon as a field.

**Comment by CloudNiner** [comment]
Yes, I think it would be an additional, optional attribute per polygon.

We already use the polygon extent to automatically retrieve appropriate OSM data if possible. The issue is that the API endpoint we use fails if the extent we request is too large. So we need to have manual extracts prepared for the larger boundaries. We'll likely just use the Mapzen metro extracts where possible.
